version: "3.8"
services:
  dev:
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./env/dev.env
  prod:
    build:
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    env_file:
      - ./env/prod.env

