/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ActivityResponseObjectAllOf
 */
@JsonPropertyOrder({
  ActivityResponseObjectAllOf.JSON_PROPERTY_DUE_DATE,
  ActivityResponseObjectAllOf.JSON_PROPERTY_DUE_TIME,
  ActivityResponseObjectAllOf.JSON_PROPERTY_DURATION,
  ActivityResponseObjectAllOf.JSON_PROPERTY_DEAL_ID,
  ActivityResponseObjectAllOf.JSON_PROPERTY_LEAD_ID,
  ActivityResponseObjectAllOf.JSON_PROPERTY_PERSON_ID,
  ActivityResponseObjectAllOf.JSON_PROPERTY_ORG_ID,
  ActivityResponseObjectAllOf.JSON_PROPERTY_NOTE,
  ActivityResponseObjectAllOf.JSON_PROPERTY_LOCATION,
  ActivityResponseObjectAllOf.JSON_PROPERTY_PUBLIC_DESCRIPTION
})
@JsonTypeName("activityResponseObject_allOf")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class ActivityResponseObjectAllOf {
  public static final String JSON_PROPERTY_DUE_DATE = "due_date";
  private LocalDate dueDate;

  public static final String JSON_PROPERTY_DUE_TIME = "due_time";
  private String dueTime;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private String duration;

  public static final String JSON_PROPERTY_DEAL_ID = "deal_id";
  private Integer dealId;

  public static final String JSON_PROPERTY_LEAD_ID = "lead_id";
  private String leadId;

  public static final String JSON_PROPERTY_PERSON_ID = "person_id";
  private Integer personId;

  public static final String JSON_PROPERTY_ORG_ID = "org_id";
  private Integer orgId;

  public static final String JSON_PROPERTY_NOTE = "note";
  private String note;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_PUBLIC_DESCRIPTION = "public_description";
  private String publicDescription;

  public ActivityResponseObjectAllOf() {
  }

  public ActivityResponseObjectAllOf dueDate(LocalDate dueDate) {
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The due date of the activity. Format: YYYY-MM-DD
   * @return dueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The due date of the activity. Format: YYYY-MM-DD")
  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDueDate() {
    return dueDate;
  }


  @JsonProperty(JSON_PROPERTY_DUE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
  }


  public ActivityResponseObjectAllOf dueTime(String dueTime) {
    
    this.dueTime = dueTime;
    return this;
  }

   /**
   * The due time of the activity in UTC. Format: HH:MM
   * @return dueTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The due time of the activity in UTC. Format: HH:MM")
  @JsonProperty(JSON_PROPERTY_DUE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDueTime() {
    return dueTime;
  }


  @JsonProperty(JSON_PROPERTY_DUE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueTime(String dueTime) {
    this.dueTime = dueTime;
  }


  public ActivityResponseObjectAllOf duration(String duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * The duration of the activity. Format: HH:MM
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The duration of the activity. Format: HH:MM")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(String duration) {
    this.duration = duration;
  }


  public ActivityResponseObjectAllOf dealId(Integer dealId) {
    
    this.dealId = dealId;
    return this;
  }

   /**
   * The ID of the deal this activity is associated with
   * @return dealId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the deal this activity is associated with")
  @JsonProperty(JSON_PROPERTY_DEAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDealId() {
    return dealId;
  }


  @JsonProperty(JSON_PROPERTY_DEAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDealId(Integer dealId) {
    this.dealId = dealId;
  }


  public ActivityResponseObjectAllOf leadId(String leadId) {
    
    this.leadId = leadId;
    return this;
  }

   /**
   * The ID of the lead this activity is associated with
   * @return leadId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the lead this activity is associated with")
  @JsonProperty(JSON_PROPERTY_LEAD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLeadId() {
    return leadId;
  }


  @JsonProperty(JSON_PROPERTY_LEAD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeadId(String leadId) {
    this.leadId = leadId;
  }


  public ActivityResponseObjectAllOf personId(Integer personId) {
    
    this.personId = personId;
    return this;
  }

   /**
   * The ID of the person this activity is associated with
   * @return personId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the person this activity is associated with")
  @JsonProperty(JSON_PROPERTY_PERSON_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPersonId() {
    return personId;
  }


  @JsonProperty(JSON_PROPERTY_PERSON_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonId(Integer personId) {
    this.personId = personId;
  }


  public ActivityResponseObjectAllOf orgId(Integer orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * The ID of the organization this activity is associated with
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the organization this activity is associated with")
  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrgId() {
    return orgId;
  }


  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgId(Integer orgId) {
    this.orgId = orgId;
  }


  public ActivityResponseObjectAllOf note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * The note of the activity (HTML format)
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The note of the activity (HTML format)")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(String note) {
    this.note = note;
  }


  public ActivityResponseObjectAllOf location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * The address of the activity. Pipedrive will automatically check if the location matches a geo-location on Google maps.
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address of the activity. Pipedrive will automatically check if the location matches a geo-location on Google maps.")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(String location) {
    this.location = location;
  }


  public ActivityResponseObjectAllOf publicDescription(String publicDescription) {
    
    this.publicDescription = publicDescription;
    return this;
  }

   /**
   * Additional details about the activity that is synced to your external calendar. Unlike the note added to the activity, the description is publicly visible to any guests added to the activity.
   * @return publicDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional details about the activity that is synced to your external calendar. Unlike the note added to the activity, the description is publicly visible to any guests added to the activity.")
  @JsonProperty(JSON_PROPERTY_PUBLIC_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicDescription() {
    return publicDescription;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicDescription(String publicDescription) {
    this.publicDescription = publicDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityResponseObjectAllOf activityResponseObjectAllOf = (ActivityResponseObjectAllOf) o;
    return Objects.equals(this.dueDate, activityResponseObjectAllOf.dueDate) &&
        Objects.equals(this.dueTime, activityResponseObjectAllOf.dueTime) &&
        Objects.equals(this.duration, activityResponseObjectAllOf.duration) &&
        Objects.equals(this.dealId, activityResponseObjectAllOf.dealId) &&
        Objects.equals(this.leadId, activityResponseObjectAllOf.leadId) &&
        Objects.equals(this.personId, activityResponseObjectAllOf.personId) &&
        Objects.equals(this.orgId, activityResponseObjectAllOf.orgId) &&
        Objects.equals(this.note, activityResponseObjectAllOf.note) &&
        Objects.equals(this.location, activityResponseObjectAllOf.location) &&
        Objects.equals(this.publicDescription, activityResponseObjectAllOf.publicDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dueDate, dueTime, duration, dealId, leadId, personId, orgId, note, location, publicDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityResponseObjectAllOf {\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    dueTime: ").append(toIndentedString(dueTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    dealId: ").append(toIndentedString(dealId)).append("\n");
    sb.append("    leadId: ").append(toIndentedString(leadId)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    publicDescription: ").append(toIndentedString(publicDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

