/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.Owner;
import com.zenika.pipedrive.model.PersonItemAllOfEmailInner;
import com.zenika.pipedrive.model.PersonItemAllOfPhoneInner;
import com.zenika.pipedrive.model.PersonItemAllOfPictureId;
import com.zenika.pipedrive.model.RelationshipOrganizationInfoItemWithActiveFlag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The object of participant
 */
@ApiModel(description = "The object of participant")
@JsonPropertyOrder({
  AddDealParticipantResponse200Data.JSON_PROPERTY_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_COMPANY_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_ACTIVE_FLAG,
  AddDealParticipantResponse200Data.JSON_PROPERTY_PHONE,
  AddDealParticipantResponse200Data.JSON_PROPERTY_EMAIL,
  AddDealParticipantResponse200Data.JSON_PROPERTY_FIRST_CHAR,
  AddDealParticipantResponse200Data.JSON_PROPERTY_ADD_TIME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_UPDATE_TIME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_VISIBLE_TO,
  AddDealParticipantResponse200Data.JSON_PROPERTY_PICTURE_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LABEL,
  AddDealParticipantResponse200Data.JSON_PROPERTY_ORG_NAME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_OWNER_NAME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_CC_EMAIL,
  AddDealParticipantResponse200Data.JSON_PROPERTY_OWNER_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_ORG_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_NAME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_FIRST_NAME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LAST_NAME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_EMAIL_MESSAGES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_ACTIVITIES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_DONE_ACTIVITIES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_FILES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_NOTES_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_FOLLOWERS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LAST_INCOMING_MAIL_TIME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_OPEN_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_CLOSED_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_WON_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_RELATED_WON_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LOST_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_RELATED_LOST_DEALS_COUNT,
  AddDealParticipantResponse200Data.JSON_PROPERTY_NEXT_ACTIVITY_DATE,
  AddDealParticipantResponse200Data.JSON_PROPERTY_NEXT_ACTIVITY_TIME,
  AddDealParticipantResponse200Data.JSON_PROPERTY_NEXT_ACTIVITY_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LAST_ACTIVITY_ID,
  AddDealParticipantResponse200Data.JSON_PROPERTY_LAST_ACTIVITY_DATE
})
@JsonTypeName("addDealParticipantResponse200_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class AddDealParticipantResponse200Data {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_COMPANY_ID = "company_id";
  private Integer companyId;

  public static final String JSON_PROPERTY_ACTIVE_FLAG = "active_flag";
  private Boolean activeFlag;

  public static final String JSON_PROPERTY_PHONE = "phone";
  private List<PersonItemAllOfPhoneInner> phone = null;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private List<PersonItemAllOfEmailInner> email = null;

  public static final String JSON_PROPERTY_FIRST_CHAR = "first_char";
  private String firstChar;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private String addTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  private String updateTime;

  public static final String JSON_PROPERTY_VISIBLE_TO = "visible_to";
  private String visibleTo;

  public static final String JSON_PROPERTY_PICTURE_ID = "picture_id";
  private PersonItemAllOfPictureId pictureId;

  public static final String JSON_PROPERTY_LABEL = "label";
  private Integer label;

  public static final String JSON_PROPERTY_ORG_NAME = "org_name";
  private String orgName;

  public static final String JSON_PROPERTY_OWNER_NAME = "owner_name";
  private String ownerName;

  public static final String JSON_PROPERTY_CC_EMAIL = "cc_email";
  private String ccEmail;

  public static final String JSON_PROPERTY_OWNER_ID = "owner_id";
  private Owner ownerId;

  public static final String JSON_PROPERTY_ORG_ID = "org_id";
  private RelationshipOrganizationInfoItemWithActiveFlag orgId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_FIRST_NAME = "first_name";
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "last_name";
  private String lastName;

  public static final String JSON_PROPERTY_EMAIL_MESSAGES_COUNT = "email_messages_count";
  private Integer emailMessagesCount;

  public static final String JSON_PROPERTY_ACTIVITIES_COUNT = "activities_count";
  private Integer activitiesCount;

  public static final String JSON_PROPERTY_DONE_ACTIVITIES_COUNT = "done_activities_count";
  private Integer doneActivitiesCount;

  public static final String JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT = "undone_activities_count";
  private Integer undoneActivitiesCount;

  public static final String JSON_PROPERTY_FILES_COUNT = "files_count";
  private Integer filesCount;

  public static final String JSON_PROPERTY_NOTES_COUNT = "notes_count";
  private Integer notesCount;

  public static final String JSON_PROPERTY_FOLLOWERS_COUNT = "followers_count";
  private Integer followersCount;

  public static final String JSON_PROPERTY_LAST_INCOMING_MAIL_TIME = "last_incoming_mail_time";
  private String lastIncomingMailTime;

  public static final String JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME = "last_outgoing_mail_time";
  private String lastOutgoingMailTime;

  public static final String JSON_PROPERTY_OPEN_DEALS_COUNT = "open_deals_count";
  private Integer openDealsCount;

  public static final String JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT = "related_open_deals_count";
  private Integer relatedOpenDealsCount;

  public static final String JSON_PROPERTY_CLOSED_DEALS_COUNT = "closed_deals_count";
  private Integer closedDealsCount;

  public static final String JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT = "related_closed_deals_count";
  private Integer relatedClosedDealsCount;

  public static final String JSON_PROPERTY_WON_DEALS_COUNT = "won_deals_count";
  private Integer wonDealsCount;

  public static final String JSON_PROPERTY_RELATED_WON_DEALS_COUNT = "related_won_deals_count";
  private Integer relatedWonDealsCount;

  public static final String JSON_PROPERTY_LOST_DEALS_COUNT = "lost_deals_count";
  private Integer lostDealsCount;

  public static final String JSON_PROPERTY_RELATED_LOST_DEALS_COUNT = "related_lost_deals_count";
  private Integer relatedLostDealsCount;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_DATE = "next_activity_date";
  private String nextActivityDate;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_TIME = "next_activity_time";
  private String nextActivityTime;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_ID = "next_activity_id";
  private JsonNullable<Integer> nextActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_ID = "last_activity_id";
  private JsonNullable<Integer> lastActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_DATE = "last_activity_date";
  private JsonNullable<String> lastActivityDate = JsonNullable.<String>undefined();

  public AddDealParticipantResponse200Data() {
  }

  public AddDealParticipantResponse200Data id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the person
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the person")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public AddDealParticipantResponse200Data companyId(Integer companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The ID of the company related to the person
   * @return companyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the company related to the person")
  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCompanyId() {
    return companyId;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }


  public AddDealParticipantResponse200Data activeFlag(Boolean activeFlag) {
    
    this.activeFlag = activeFlag;
    return this;
  }

   /**
   * Whether the person is active or not
   * @return activeFlag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the person is active or not")
  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActiveFlag() {
    return activeFlag;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveFlag(Boolean activeFlag) {
    this.activeFlag = activeFlag;
  }


  public AddDealParticipantResponse200Data phone(List<PersonItemAllOfPhoneInner> phone) {
    
    this.phone = phone;
    return this;
  }

  public AddDealParticipantResponse200Data addPhoneItem(PersonItemAllOfPhoneInner phoneItem) {
    if (this.phone == null) {
      this.phone = new ArrayList<>();
    }
    this.phone.add(phoneItem);
    return this;
  }

   /**
   * A phone number supplied as a string or an array of phone objects related to the person. The structure of the array is as follows: &#x60;[{ \&quot;value\&quot;: \&quot;12345\&quot;, \&quot;primary\&quot;: \&quot;true\&quot;, \&quot;label\&quot;: \&quot;mobile\&quot; }]&#x60;. Please note that only &#x60;value&#x60; is required.
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A phone number supplied as a string or an array of phone objects related to the person. The structure of the array is as follows: `[{ \"value\": \"12345\", \"primary\": \"true\", \"label\": \"mobile\" }]`. Please note that only `value` is required.")
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PersonItemAllOfPhoneInner> getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(List<PersonItemAllOfPhoneInner> phone) {
    this.phone = phone;
  }


  public AddDealParticipantResponse200Data email(List<PersonItemAllOfEmailInner> email) {
    
    this.email = email;
    return this;
  }

  public AddDealParticipantResponse200Data addEmailItem(PersonItemAllOfEmailInner emailItem) {
    if (this.email == null) {
      this.email = new ArrayList<>();
    }
    this.email.add(emailItem);
    return this;
  }

   /**
   * An email address as a string or an array of email objects related to the person. The structure of the array is as follows: &#x60;[{ \&quot;value\&quot;: \&quot;mail@example.com\&quot;, \&quot;primary\&quot;: \&quot;true\&quot;, \&quot;label\&quot;: \&quot;main\&quot; } ]&#x60;. Please note that only &#x60;value&#x60; is required.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An email address as a string or an array of email objects related to the person. The structure of the array is as follows: `[{ \"value\": \"mail@example.com\", \"primary\": \"true\", \"label\": \"main\" } ]`. Please note that only `value` is required.")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PersonItemAllOfEmailInner> getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(List<PersonItemAllOfEmailInner> email) {
    this.email = email;
  }


  public AddDealParticipantResponse200Data firstChar(String firstChar) {
    
    this.firstChar = firstChar;
    return this;
  }

   /**
   * The first letter of the name of the person
   * @return firstChar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first letter of the name of the person")
  @JsonProperty(JSON_PROPERTY_FIRST_CHAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstChar() {
    return firstChar;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_CHAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstChar(String firstChar) {
    this.firstChar = firstChar;
  }


  public AddDealParticipantResponse200Data addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The date and time when the person was added/created. Format: YYYY-MM-DD HH:MM:SS
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time when the person was added/created. Format: YYYY-MM-DD HH:MM:SS")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  public AddDealParticipantResponse200Data updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The last updated date and time of the person. Format: YYYY-MM-DD HH:MM:SS
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the person. Format: YYYY-MM-DD HH:MM:SS")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public AddDealParticipantResponse200Data visibleTo(String visibleTo) {
    
    this.visibleTo = visibleTo;
    return this;
  }

   /**
   * The visibility group ID of who can see the person
   * @return visibleTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The visibility group ID of who can see the person")
  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibleTo() {
    return visibleTo;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleTo(String visibleTo) {
    this.visibleTo = visibleTo;
  }


  public AddDealParticipantResponse200Data pictureId(PersonItemAllOfPictureId pictureId) {
    
    this.pictureId = pictureId;
    return this;
  }

   /**
   * Get pictureId
   * @return pictureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PICTURE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PersonItemAllOfPictureId getPictureId() {
    return pictureId;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPictureId(PersonItemAllOfPictureId pictureId) {
    this.pictureId = pictureId;
  }


  public AddDealParticipantResponse200Data label(Integer label) {
    
    this.label = label;
    return this;
  }

   /**
   * The label assigned to the person
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The label assigned to the person")
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(Integer label) {
    this.label = label;
  }


  public AddDealParticipantResponse200Data orgName(String orgName) {
    
    this.orgName = orgName;
    return this;
  }

   /**
   * The name of the organization associated with the person
   * @return orgName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the organization associated with the person")
  @JsonProperty(JSON_PROPERTY_ORG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrgName() {
    return orgName;
  }


  @JsonProperty(JSON_PROPERTY_ORG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


  public AddDealParticipantResponse200Data ownerName(String ownerName) {
    
    this.ownerName = ownerName;
    return this;
  }

   /**
   * The name of the owner associated with the person
   * @return ownerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the owner associated with the person")
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerName() {
    return ownerName;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }


  public AddDealParticipantResponse200Data ccEmail(String ccEmail) {
    
    this.ccEmail = ccEmail;
    return this;
  }

   /**
   * The BCC email associated with the person
   * @return ccEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The BCC email associated with the person")
  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCcEmail() {
    return ccEmail;
  }


  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCcEmail(String ccEmail) {
    this.ccEmail = ccEmail;
  }


  public AddDealParticipantResponse200Data ownerId(Owner ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Owner getOwnerId() {
    return ownerId;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerId(Owner ownerId) {
    this.ownerId = ownerId;
  }


  public AddDealParticipantResponse200Data orgId(RelationshipOrganizationInfoItemWithActiveFlag orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * Get orgId
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipOrganizationInfoItemWithActiveFlag getOrgId() {
    return orgId;
  }


  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgId(RelationshipOrganizationInfoItemWithActiveFlag orgId) {
    this.orgId = orgId;
  }


  public AddDealParticipantResponse200Data name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the person
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the person")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public AddDealParticipantResponse200Data firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the person
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first name of the person")
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public AddDealParticipantResponse200Data lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the person
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last name of the person")
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public AddDealParticipantResponse200Data emailMessagesCount(Integer emailMessagesCount) {
    
    this.emailMessagesCount = emailMessagesCount;
    return this;
  }

   /**
   * The count of email messages related to the person
   * @return emailMessagesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of email messages related to the person")
  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEmailMessagesCount() {
    return emailMessagesCount;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailMessagesCount(Integer emailMessagesCount) {
    this.emailMessagesCount = emailMessagesCount;
  }


  public AddDealParticipantResponse200Data activitiesCount(Integer activitiesCount) {
    
    this.activitiesCount = activitiesCount;
    return this;
  }

   /**
   * The count of activities related to the person
   * @return activitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of activities related to the person")
  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivitiesCount() {
    return activitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivitiesCount(Integer activitiesCount) {
    this.activitiesCount = activitiesCount;
  }


  public AddDealParticipantResponse200Data doneActivitiesCount(Integer doneActivitiesCount) {
    
    this.doneActivitiesCount = doneActivitiesCount;
    return this;
  }

   /**
   * The count of done activities related to the person
   * @return doneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of done activities related to the person")
  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDoneActivitiesCount() {
    return doneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneActivitiesCount(Integer doneActivitiesCount) {
    this.doneActivitiesCount = doneActivitiesCount;
  }


  public AddDealParticipantResponse200Data undoneActivitiesCount(Integer undoneActivitiesCount) {
    
    this.undoneActivitiesCount = undoneActivitiesCount;
    return this;
  }

   /**
   * The count of undone activities related to the person
   * @return undoneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of undone activities related to the person")
  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUndoneActivitiesCount() {
    return undoneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUndoneActivitiesCount(Integer undoneActivitiesCount) {
    this.undoneActivitiesCount = undoneActivitiesCount;
  }


  public AddDealParticipantResponse200Data filesCount(Integer filesCount) {
    
    this.filesCount = filesCount;
    return this;
  }

   /**
   * The count of files related to the person
   * @return filesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of files related to the person")
  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFilesCount() {
    return filesCount;
  }


  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilesCount(Integer filesCount) {
    this.filesCount = filesCount;
  }


  public AddDealParticipantResponse200Data notesCount(Integer notesCount) {
    
    this.notesCount = notesCount;
    return this;
  }

   /**
   * The count of notes related to the person
   * @return notesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of notes related to the person")
  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNotesCount() {
    return notesCount;
  }


  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotesCount(Integer notesCount) {
    this.notesCount = notesCount;
  }


  public AddDealParticipantResponse200Data followersCount(Integer followersCount) {
    
    this.followersCount = followersCount;
    return this;
  }

   /**
   * The count of followers related to the person
   * @return followersCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of followers related to the person")
  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFollowersCount() {
    return followersCount;
  }


  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowersCount(Integer followersCount) {
    this.followersCount = followersCount;
  }


  public AddDealParticipantResponse200Data lastIncomingMailTime(String lastIncomingMailTime) {
    
    this.lastIncomingMailTime = lastIncomingMailTime;
    return this;
  }

   /**
   * The date and time of the last incoming email associated with the person
   * @return lastIncomingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last incoming email associated with the person")
  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastIncomingMailTime() {
    return lastIncomingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastIncomingMailTime(String lastIncomingMailTime) {
    this.lastIncomingMailTime = lastIncomingMailTime;
  }


  public AddDealParticipantResponse200Data lastOutgoingMailTime(String lastOutgoingMailTime) {
    
    this.lastOutgoingMailTime = lastOutgoingMailTime;
    return this;
  }

   /**
   * The date and time of the last outgoing email associated with the person
   * @return lastOutgoingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last outgoing email associated with the person")
  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastOutgoingMailTime() {
    return lastOutgoingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastOutgoingMailTime(String lastOutgoingMailTime) {
    this.lastOutgoingMailTime = lastOutgoingMailTime;
  }


  public AddDealParticipantResponse200Data openDealsCount(Integer openDealsCount) {
    
    this.openDealsCount = openDealsCount;
    return this;
  }

   /**
   * The count of open deals related with the item
   * @return openDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of open deals related with the item")
  @JsonProperty(JSON_PROPERTY_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOpenDealsCount() {
    return openDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenDealsCount(Integer openDealsCount) {
    this.openDealsCount = openDealsCount;
  }


  public AddDealParticipantResponse200Data relatedOpenDealsCount(Integer relatedOpenDealsCount) {
    
    this.relatedOpenDealsCount = relatedOpenDealsCount;
    return this;
  }

   /**
   * The count of related open deals related with the item
   * @return relatedOpenDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related open deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedOpenDealsCount() {
    return relatedOpenDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedOpenDealsCount(Integer relatedOpenDealsCount) {
    this.relatedOpenDealsCount = relatedOpenDealsCount;
  }


  public AddDealParticipantResponse200Data closedDealsCount(Integer closedDealsCount) {
    
    this.closedDealsCount = closedDealsCount;
    return this;
  }

   /**
   * The count of closed deals related with the item
   * @return closedDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of closed deals related with the item")
  @JsonProperty(JSON_PROPERTY_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getClosedDealsCount() {
    return closedDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosedDealsCount(Integer closedDealsCount) {
    this.closedDealsCount = closedDealsCount;
  }


  public AddDealParticipantResponse200Data relatedClosedDealsCount(Integer relatedClosedDealsCount) {
    
    this.relatedClosedDealsCount = relatedClosedDealsCount;
    return this;
  }

   /**
   * The count of related closed deals related with the item
   * @return relatedClosedDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related closed deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedClosedDealsCount() {
    return relatedClosedDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedClosedDealsCount(Integer relatedClosedDealsCount) {
    this.relatedClosedDealsCount = relatedClosedDealsCount;
  }


  public AddDealParticipantResponse200Data wonDealsCount(Integer wonDealsCount) {
    
    this.wonDealsCount = wonDealsCount;
    return this;
  }

   /**
   * The count of won deals related with the item
   * @return wonDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of won deals related with the item")
  @JsonProperty(JSON_PROPERTY_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWonDealsCount() {
    return wonDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWonDealsCount(Integer wonDealsCount) {
    this.wonDealsCount = wonDealsCount;
  }


  public AddDealParticipantResponse200Data relatedWonDealsCount(Integer relatedWonDealsCount) {
    
    this.relatedWonDealsCount = relatedWonDealsCount;
    return this;
  }

   /**
   * The count of related won deals related with the item
   * @return relatedWonDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related won deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedWonDealsCount() {
    return relatedWonDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedWonDealsCount(Integer relatedWonDealsCount) {
    this.relatedWonDealsCount = relatedWonDealsCount;
  }


  public AddDealParticipantResponse200Data lostDealsCount(Integer lostDealsCount) {
    
    this.lostDealsCount = lostDealsCount;
    return this;
  }

   /**
   * The count of lost deals related with the item
   * @return lostDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of lost deals related with the item")
  @JsonProperty(JSON_PROPERTY_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLostDealsCount() {
    return lostDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLostDealsCount(Integer lostDealsCount) {
    this.lostDealsCount = lostDealsCount;
  }


  public AddDealParticipantResponse200Data relatedLostDealsCount(Integer relatedLostDealsCount) {
    
    this.relatedLostDealsCount = relatedLostDealsCount;
    return this;
  }

   /**
   * The count of related lost deals related with the item
   * @return relatedLostDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related lost deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedLostDealsCount() {
    return relatedLostDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedLostDealsCount(Integer relatedLostDealsCount) {
    this.relatedLostDealsCount = relatedLostDealsCount;
  }


  public AddDealParticipantResponse200Data nextActivityDate(String nextActivityDate) {
    
    this.nextActivityDate = nextActivityDate;
    return this;
  }

   /**
   * The date of the next activity associated with the deal
   * @return nextActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityDate() {
    return nextActivityDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityDate(String nextActivityDate) {
    this.nextActivityDate = nextActivityDate;
  }


  public AddDealParticipantResponse200Data nextActivityTime(String nextActivityTime) {
    
    this.nextActivityTime = nextActivityTime;
    return this;
  }

   /**
   * The time of the next activity associated with the deal
   * @return nextActivityTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityTime() {
    return nextActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityTime(String nextActivityTime) {
    this.nextActivityTime = nextActivityTime;
  }


  public AddDealParticipantResponse200Data nextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
    
    return this;
  }

   /**
   * The ID of the next activity associated with the deal
   * @return nextActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the next activity associated with the deal")
  @JsonIgnore

  public Integer getNextActivityId() {
        return nextActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getNextActivityId_JsonNullable() {
    return nextActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  public void setNextActivityId_JsonNullable(JsonNullable<Integer> nextActivityId) {
    this.nextActivityId = nextActivityId;
  }

  public void setNextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
  }


  public AddDealParticipantResponse200Data lastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
    
    return this;
  }

   /**
   * The ID of the last activity associated with the deal
   * @return lastActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the last activity associated with the deal")
  @JsonIgnore

  public Integer getLastActivityId() {
        return lastActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLastActivityId_JsonNullable() {
    return lastActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  public void setLastActivityId_JsonNullable(JsonNullable<Integer> lastActivityId) {
    this.lastActivityId = lastActivityId;
  }

  public void setLastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
  }


  public AddDealParticipantResponse200Data lastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
    
    return this;
  }

   /**
   * The date of the last activity associated with the deal
   * @return lastActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the last activity associated with the deal")
  @JsonIgnore

  public String getLastActivityDate() {
        return lastActivityDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastActivityDate_JsonNullable() {
    return lastActivityDate;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  public void setLastActivityDate_JsonNullable(JsonNullable<String> lastActivityDate) {
    this.lastActivityDate = lastActivityDate;
  }

  public void setLastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddDealParticipantResponse200Data addDealParticipantResponse200Data = (AddDealParticipantResponse200Data) o;
    return Objects.equals(this.id, addDealParticipantResponse200Data.id) &&
        Objects.equals(this.companyId, addDealParticipantResponse200Data.companyId) &&
        Objects.equals(this.activeFlag, addDealParticipantResponse200Data.activeFlag) &&
        Objects.equals(this.phone, addDealParticipantResponse200Data.phone) &&
        Objects.equals(this.email, addDealParticipantResponse200Data.email) &&
        Objects.equals(this.firstChar, addDealParticipantResponse200Data.firstChar) &&
        Objects.equals(this.addTime, addDealParticipantResponse200Data.addTime) &&
        Objects.equals(this.updateTime, addDealParticipantResponse200Data.updateTime) &&
        Objects.equals(this.visibleTo, addDealParticipantResponse200Data.visibleTo) &&
        Objects.equals(this.pictureId, addDealParticipantResponse200Data.pictureId) &&
        Objects.equals(this.label, addDealParticipantResponse200Data.label) &&
        Objects.equals(this.orgName, addDealParticipantResponse200Data.orgName) &&
        Objects.equals(this.ownerName, addDealParticipantResponse200Data.ownerName) &&
        Objects.equals(this.ccEmail, addDealParticipantResponse200Data.ccEmail) &&
        Objects.equals(this.ownerId, addDealParticipantResponse200Data.ownerId) &&
        Objects.equals(this.orgId, addDealParticipantResponse200Data.orgId) &&
        Objects.equals(this.name, addDealParticipantResponse200Data.name) &&
        Objects.equals(this.firstName, addDealParticipantResponse200Data.firstName) &&
        Objects.equals(this.lastName, addDealParticipantResponse200Data.lastName) &&
        Objects.equals(this.emailMessagesCount, addDealParticipantResponse200Data.emailMessagesCount) &&
        Objects.equals(this.activitiesCount, addDealParticipantResponse200Data.activitiesCount) &&
        Objects.equals(this.doneActivitiesCount, addDealParticipantResponse200Data.doneActivitiesCount) &&
        Objects.equals(this.undoneActivitiesCount, addDealParticipantResponse200Data.undoneActivitiesCount) &&
        Objects.equals(this.filesCount, addDealParticipantResponse200Data.filesCount) &&
        Objects.equals(this.notesCount, addDealParticipantResponse200Data.notesCount) &&
        Objects.equals(this.followersCount, addDealParticipantResponse200Data.followersCount) &&
        Objects.equals(this.lastIncomingMailTime, addDealParticipantResponse200Data.lastIncomingMailTime) &&
        Objects.equals(this.lastOutgoingMailTime, addDealParticipantResponse200Data.lastOutgoingMailTime) &&
        Objects.equals(this.openDealsCount, addDealParticipantResponse200Data.openDealsCount) &&
        Objects.equals(this.relatedOpenDealsCount, addDealParticipantResponse200Data.relatedOpenDealsCount) &&
        Objects.equals(this.closedDealsCount, addDealParticipantResponse200Data.closedDealsCount) &&
        Objects.equals(this.relatedClosedDealsCount, addDealParticipantResponse200Data.relatedClosedDealsCount) &&
        Objects.equals(this.wonDealsCount, addDealParticipantResponse200Data.wonDealsCount) &&
        Objects.equals(this.relatedWonDealsCount, addDealParticipantResponse200Data.relatedWonDealsCount) &&
        Objects.equals(this.lostDealsCount, addDealParticipantResponse200Data.lostDealsCount) &&
        Objects.equals(this.relatedLostDealsCount, addDealParticipantResponse200Data.relatedLostDealsCount) &&
        Objects.equals(this.nextActivityDate, addDealParticipantResponse200Data.nextActivityDate) &&
        Objects.equals(this.nextActivityTime, addDealParticipantResponse200Data.nextActivityTime) &&
        equalsNullable(this.nextActivityId, addDealParticipantResponse200Data.nextActivityId) &&
        equalsNullable(this.lastActivityId, addDealParticipantResponse200Data.lastActivityId) &&
        equalsNullable(this.lastActivityDate, addDealParticipantResponse200Data.lastActivityDate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, companyId, activeFlag, phone, email, firstChar, addTime, updateTime, visibleTo, pictureId, label, orgName, ownerName, ccEmail, ownerId, orgId, name, firstName, lastName, emailMessagesCount, activitiesCount, doneActivitiesCount, undoneActivitiesCount, filesCount, notesCount, followersCount, lastIncomingMailTime, lastOutgoingMailTime, openDealsCount, relatedOpenDealsCount, closedDealsCount, relatedClosedDealsCount, wonDealsCount, relatedWonDealsCount, lostDealsCount, relatedLostDealsCount, nextActivityDate, nextActivityTime, hashCodeNullable(nextActivityId), hashCodeNullable(lastActivityId), hashCodeNullable(lastActivityDate));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddDealParticipantResponse200Data {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    activeFlag: ").append(toIndentedString(activeFlag)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstChar: ").append(toIndentedString(firstChar)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    visibleTo: ").append(toIndentedString(visibleTo)).append("\n");
    sb.append("    pictureId: ").append(toIndentedString(pictureId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    ccEmail: ").append(toIndentedString(ccEmail)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emailMessagesCount: ").append(toIndentedString(emailMessagesCount)).append("\n");
    sb.append("    activitiesCount: ").append(toIndentedString(activitiesCount)).append("\n");
    sb.append("    doneActivitiesCount: ").append(toIndentedString(doneActivitiesCount)).append("\n");
    sb.append("    undoneActivitiesCount: ").append(toIndentedString(undoneActivitiesCount)).append("\n");
    sb.append("    filesCount: ").append(toIndentedString(filesCount)).append("\n");
    sb.append("    notesCount: ").append(toIndentedString(notesCount)).append("\n");
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    lastIncomingMailTime: ").append(toIndentedString(lastIncomingMailTime)).append("\n");
    sb.append("    lastOutgoingMailTime: ").append(toIndentedString(lastOutgoingMailTime)).append("\n");
    sb.append("    openDealsCount: ").append(toIndentedString(openDealsCount)).append("\n");
    sb.append("    relatedOpenDealsCount: ").append(toIndentedString(relatedOpenDealsCount)).append("\n");
    sb.append("    closedDealsCount: ").append(toIndentedString(closedDealsCount)).append("\n");
    sb.append("    relatedClosedDealsCount: ").append(toIndentedString(relatedClosedDealsCount)).append("\n");
    sb.append("    wonDealsCount: ").append(toIndentedString(wonDealsCount)).append("\n");
    sb.append("    relatedWonDealsCount: ").append(toIndentedString(relatedWonDealsCount)).append("\n");
    sb.append("    lostDealsCount: ").append(toIndentedString(lostDealsCount)).append("\n");
    sb.append("    relatedLostDealsCount: ").append(toIndentedString(relatedLostDealsCount)).append("\n");
    sb.append("    nextActivityDate: ").append(toIndentedString(nextActivityDate)).append("\n");
    sb.append("    nextActivityTime: ").append(toIndentedString(nextActivityTime)).append("\n");
    sb.append("    nextActivityId: ").append(toIndentedString(nextActivityId)).append("\n");
    sb.append("    lastActivityId: ").append(toIndentedString(lastActivityId)).append("\n");
    sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

