/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BaseDeal
 */
@JsonPropertyOrder({
  BaseDeal.JSON_PROPERTY_STAGE_ID,
  BaseDeal.JSON_PROPERTY_TITLE,
  BaseDeal.JSON_PROPERTY_VALUE,
  BaseDeal.JSON_PROPERTY_CURRENCY,
  BaseDeal.JSON_PROPERTY_ADD_TIME,
  BaseDeal.JSON_PROPERTY_UPDATE_TIME,
  BaseDeal.JSON_PROPERTY_STAGE_CHANGE_TIME,
  BaseDeal.JSON_PROPERTY_ACTIVE,
  BaseDeal.JSON_PROPERTY_DELETED,
  BaseDeal.JSON_PROPERTY_STATUS,
  BaseDeal.JSON_PROPERTY_PROBABILITY,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_DATE,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_TIME,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_ID,
  BaseDeal.JSON_PROPERTY_LAST_ACTIVITY_ID,
  BaseDeal.JSON_PROPERTY_LAST_ACTIVITY_DATE,
  BaseDeal.JSON_PROPERTY_LOST_REASON,
  BaseDeal.JSON_PROPERTY_VISIBLE_TO,
  BaseDeal.JSON_PROPERTY_CLOSE_TIME,
  BaseDeal.JSON_PROPERTY_PIPELINE_ID,
  BaseDeal.JSON_PROPERTY_WON_TIME,
  BaseDeal.JSON_PROPERTY_FIRST_WON_TIME,
  BaseDeal.JSON_PROPERTY_LOST_TIME,
  BaseDeal.JSON_PROPERTY_PRODUCTS_COUNT,
  BaseDeal.JSON_PROPERTY_FILES_COUNT,
  BaseDeal.JSON_PROPERTY_NOTES_COUNT,
  BaseDeal.JSON_PROPERTY_FOLLOWERS_COUNT,
  BaseDeal.JSON_PROPERTY_EMAIL_MESSAGES_COUNT,
  BaseDeal.JSON_PROPERTY_ACTIVITIES_COUNT,
  BaseDeal.JSON_PROPERTY_DONE_ACTIVITIES_COUNT,
  BaseDeal.JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT,
  BaseDeal.JSON_PROPERTY_PARTICIPANTS_COUNT,
  BaseDeal.JSON_PROPERTY_EXPECTED_CLOSE_DATE,
  BaseDeal.JSON_PROPERTY_LAST_INCOMING_MAIL_TIME,
  BaseDeal.JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME,
  BaseDeal.JSON_PROPERTY_LABEL,
  BaseDeal.JSON_PROPERTY_STAGE_ORDER_NR,
  BaseDeal.JSON_PROPERTY_PERSON_NAME,
  BaseDeal.JSON_PROPERTY_ORG_NAME,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_SUBJECT,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_TYPE,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_DURATION,
  BaseDeal.JSON_PROPERTY_NEXT_ACTIVITY_NOTE,
  BaseDeal.JSON_PROPERTY_FORMATTED_VALUE,
  BaseDeal.JSON_PROPERTY_WEIGHTED_VALUE,
  BaseDeal.JSON_PROPERTY_FORMATTED_WEIGHTED_VALUE,
  BaseDeal.JSON_PROPERTY_WEIGHTED_VALUE_CURRENCY,
  BaseDeal.JSON_PROPERTY_ROTTEN_TIME,
  BaseDeal.JSON_PROPERTY_OWNER_NAME,
  BaseDeal.JSON_PROPERTY_CC_EMAIL,
  BaseDeal.JSON_PROPERTY_ORG_HIDDEN,
  BaseDeal.JSON_PROPERTY_PERSON_HIDDEN
})
@JsonTypeName("baseDeal")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class BaseDeal {
  public static final String JSON_PROPERTY_STAGE_ID = "stage_id";
  private Integer stageId;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_VALUE = "value";
  private BigDecimal value;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private String addTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  private String updateTime;

  public static final String JSON_PROPERTY_STAGE_CHANGE_TIME = "stage_change_time";
  private String stageChangeTime;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_PROBABILITY = "probability";
  private JsonNullable<BigDecimal> probability = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_DATE = "next_activity_date";
  private String nextActivityDate;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_TIME = "next_activity_time";
  private String nextActivityTime;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_ID = "next_activity_id";
  private JsonNullable<Integer> nextActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_ID = "last_activity_id";
  private JsonNullable<Integer> lastActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_DATE = "last_activity_date";
  private JsonNullable<String> lastActivityDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOST_REASON = "lost_reason";
  private JsonNullable<String> lostReason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VISIBLE_TO = "visible_to";
  private String visibleTo;

  public static final String JSON_PROPERTY_CLOSE_TIME = "close_time";
  private JsonNullable<String> closeTime = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PIPELINE_ID = "pipeline_id";
  private Integer pipelineId;

  public static final String JSON_PROPERTY_WON_TIME = "won_time";
  private String wonTime;

  public static final String JSON_PROPERTY_FIRST_WON_TIME = "first_won_time";
  private String firstWonTime;

  public static final String JSON_PROPERTY_LOST_TIME = "lost_time";
  private String lostTime;

  public static final String JSON_PROPERTY_PRODUCTS_COUNT = "products_count";
  private Integer productsCount;

  public static final String JSON_PROPERTY_FILES_COUNT = "files_count";
  private Integer filesCount;

  public static final String JSON_PROPERTY_NOTES_COUNT = "notes_count";
  private Integer notesCount;

  public static final String JSON_PROPERTY_FOLLOWERS_COUNT = "followers_count";
  private Integer followersCount;

  public static final String JSON_PROPERTY_EMAIL_MESSAGES_COUNT = "email_messages_count";
  private Integer emailMessagesCount;

  public static final String JSON_PROPERTY_ACTIVITIES_COUNT = "activities_count";
  private Integer activitiesCount;

  public static final String JSON_PROPERTY_DONE_ACTIVITIES_COUNT = "done_activities_count";
  private Integer doneActivitiesCount;

  public static final String JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT = "undone_activities_count";
  private Integer undoneActivitiesCount;

  public static final String JSON_PROPERTY_PARTICIPANTS_COUNT = "participants_count";
  private Integer participantsCount;

  public static final String JSON_PROPERTY_EXPECTED_CLOSE_DATE = "expected_close_date";
  private LocalDate expectedCloseDate;

  public static final String JSON_PROPERTY_LAST_INCOMING_MAIL_TIME = "last_incoming_mail_time";
  private String lastIncomingMailTime;

  public static final String JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME = "last_outgoing_mail_time";
  private String lastOutgoingMailTime;

  public static final String JSON_PROPERTY_LABEL = "label";
  private Integer label;

  public static final String JSON_PROPERTY_STAGE_ORDER_NR = "stage_order_nr";
  private Integer stageOrderNr;

  public static final String JSON_PROPERTY_PERSON_NAME = "person_name";
  private String personName;

  public static final String JSON_PROPERTY_ORG_NAME = "org_name";
  private String orgName;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_SUBJECT = "next_activity_subject";
  private String nextActivitySubject;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_TYPE = "next_activity_type";
  private String nextActivityType;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_DURATION = "next_activity_duration";
  private String nextActivityDuration;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_NOTE = "next_activity_note";
  private String nextActivityNote;

  public static final String JSON_PROPERTY_FORMATTED_VALUE = "formatted_value";
  private String formattedValue;

  public static final String JSON_PROPERTY_WEIGHTED_VALUE = "weighted_value";
  private BigDecimal weightedValue;

  public static final String JSON_PROPERTY_FORMATTED_WEIGHTED_VALUE = "formatted_weighted_value";
  private String formattedWeightedValue;

  public static final String JSON_PROPERTY_WEIGHTED_VALUE_CURRENCY = "weighted_value_currency";
  private String weightedValueCurrency;

  public static final String JSON_PROPERTY_ROTTEN_TIME = "rotten_time";
  private JsonNullable<String> rottenTime = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OWNER_NAME = "owner_name";
  private String ownerName;

  public static final String JSON_PROPERTY_CC_EMAIL = "cc_email";
  private String ccEmail;

  public static final String JSON_PROPERTY_ORG_HIDDEN = "org_hidden";
  private Boolean orgHidden;

  public static final String JSON_PROPERTY_PERSON_HIDDEN = "person_hidden";
  private Boolean personHidden;

  public BaseDeal() {
  }

  public BaseDeal stageId(Integer stageId) {
    
    this.stageId = stageId;
    return this;
  }

   /**
   * The ID of the deal stage
   * @return stageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the deal stage")
  @JsonProperty(JSON_PROPERTY_STAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStageId() {
    return stageId;
  }


  @JsonProperty(JSON_PROPERTY_STAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStageId(Integer stageId) {
    this.stageId = stageId;
  }


  public BaseDeal title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The title of the deal
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The title of the deal")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public BaseDeal value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * The value of the deal
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value of the deal")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(BigDecimal value) {
    this.value = value;
  }


  public BaseDeal currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * The currency associated with the deal
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The currency associated with the deal")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public BaseDeal addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The creation date and time of the deal
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The creation date and time of the deal")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  public BaseDeal updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The last updated date and time of the deal
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the deal")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public BaseDeal stageChangeTime(String stageChangeTime) {
    
    this.stageChangeTime = stageChangeTime;
    return this;
  }

   /**
   * The last updated date and time of the deal stage
   * @return stageChangeTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the deal stage")
  @JsonProperty(JSON_PROPERTY_STAGE_CHANGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStageChangeTime() {
    return stageChangeTime;
  }


  @JsonProperty(JSON_PROPERTY_STAGE_CHANGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStageChangeTime(String stageChangeTime) {
    this.stageChangeTime = stageChangeTime;
  }


  public BaseDeal active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Whether the deal is active or not
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the deal is active or not")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public BaseDeal deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Whether the deal is deleted or not
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the deal is deleted or not")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public BaseDeal status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the deal
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of the deal")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public BaseDeal probability(BigDecimal probability) {
    this.probability = JsonNullable.<BigDecimal>of(probability);
    
    return this;
  }

   /**
   * The success probability percentage of the deal
   * @return probability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The success probability percentage of the deal")
  @JsonIgnore

  public BigDecimal getProbability() {
        return probability.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROBABILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getProbability_JsonNullable() {
    return probability;
  }
  
  @JsonProperty(JSON_PROPERTY_PROBABILITY)
  public void setProbability_JsonNullable(JsonNullable<BigDecimal> probability) {
    this.probability = probability;
  }

  public void setProbability(BigDecimal probability) {
    this.probability = JsonNullable.<BigDecimal>of(probability);
  }


  public BaseDeal nextActivityDate(String nextActivityDate) {
    
    this.nextActivityDate = nextActivityDate;
    return this;
  }

   /**
   * The date of the next activity associated with the deal
   * @return nextActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityDate() {
    return nextActivityDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityDate(String nextActivityDate) {
    this.nextActivityDate = nextActivityDate;
  }


  public BaseDeal nextActivityTime(String nextActivityTime) {
    
    this.nextActivityTime = nextActivityTime;
    return this;
  }

   /**
   * The time of the next activity associated with the deal
   * @return nextActivityTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityTime() {
    return nextActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityTime(String nextActivityTime) {
    this.nextActivityTime = nextActivityTime;
  }


  public BaseDeal nextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
    
    return this;
  }

   /**
   * The ID of the next activity associated with the deal
   * @return nextActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the next activity associated with the deal")
  @JsonIgnore

  public Integer getNextActivityId() {
        return nextActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getNextActivityId_JsonNullable() {
    return nextActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  public void setNextActivityId_JsonNullable(JsonNullable<Integer> nextActivityId) {
    this.nextActivityId = nextActivityId;
  }

  public void setNextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
  }


  public BaseDeal lastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
    
    return this;
  }

   /**
   * The ID of the last activity associated with the deal
   * @return lastActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the last activity associated with the deal")
  @JsonIgnore

  public Integer getLastActivityId() {
        return lastActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLastActivityId_JsonNullable() {
    return lastActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  public void setLastActivityId_JsonNullable(JsonNullable<Integer> lastActivityId) {
    this.lastActivityId = lastActivityId;
  }

  public void setLastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
  }


  public BaseDeal lastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
    
    return this;
  }

   /**
   * The date of the last activity associated with the deal
   * @return lastActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the last activity associated with the deal")
  @JsonIgnore

  public String getLastActivityDate() {
        return lastActivityDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastActivityDate_JsonNullable() {
    return lastActivityDate;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  public void setLastActivityDate_JsonNullable(JsonNullable<String> lastActivityDate) {
    this.lastActivityDate = lastActivityDate;
  }

  public void setLastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
  }


  public BaseDeal lostReason(String lostReason) {
    this.lostReason = JsonNullable.<String>of(lostReason);
    
    return this;
  }

   /**
   * The reason for losing the deal
   * @return lostReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The reason for losing the deal")
  @JsonIgnore

  public String getLostReason() {
        return lostReason.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOST_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLostReason_JsonNullable() {
    return lostReason;
  }
  
  @JsonProperty(JSON_PROPERTY_LOST_REASON)
  public void setLostReason_JsonNullable(JsonNullable<String> lostReason) {
    this.lostReason = lostReason;
  }

  public void setLostReason(String lostReason) {
    this.lostReason = JsonNullable.<String>of(lostReason);
  }


  public BaseDeal visibleTo(String visibleTo) {
    
    this.visibleTo = visibleTo;
    return this;
  }

   /**
   * The visibility of the deal
   * @return visibleTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The visibility of the deal")
  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibleTo() {
    return visibleTo;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleTo(String visibleTo) {
    this.visibleTo = visibleTo;
  }


  public BaseDeal closeTime(String closeTime) {
    this.closeTime = JsonNullable.<String>of(closeTime);
    
    return this;
  }

   /**
   * The date and time of closing the deal
   * @return closeTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of closing the deal")
  @JsonIgnore

  public String getCloseTime() {
        return closeTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CLOSE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCloseTime_JsonNullable() {
    return closeTime;
  }
  
  @JsonProperty(JSON_PROPERTY_CLOSE_TIME)
  public void setCloseTime_JsonNullable(JsonNullable<String> closeTime) {
    this.closeTime = closeTime;
  }

  public void setCloseTime(String closeTime) {
    this.closeTime = JsonNullable.<String>of(closeTime);
  }


  public BaseDeal pipelineId(Integer pipelineId) {
    
    this.pipelineId = pipelineId;
    return this;
  }

   /**
   * The ID of pipeline associated with the deal
   * @return pipelineId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of pipeline associated with the deal")
  @JsonProperty(JSON_PROPERTY_PIPELINE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPipelineId() {
    return pipelineId;
  }


  @JsonProperty(JSON_PROPERTY_PIPELINE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPipelineId(Integer pipelineId) {
    this.pipelineId = pipelineId;
  }


  public BaseDeal wonTime(String wonTime) {
    
    this.wonTime = wonTime;
    return this;
  }

   /**
   * The date and time of changing the deal status as won
   * @return wonTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of changing the deal status as won")
  @JsonProperty(JSON_PROPERTY_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWonTime() {
    return wonTime;
  }


  @JsonProperty(JSON_PROPERTY_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWonTime(String wonTime) {
    this.wonTime = wonTime;
  }


  public BaseDeal firstWonTime(String firstWonTime) {
    
    this.firstWonTime = firstWonTime;
    return this;
  }

   /**
   * The date and time of the first time changing the deal status as won
   * @return firstWonTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the first time changing the deal status as won")
  @JsonProperty(JSON_PROPERTY_FIRST_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstWonTime() {
    return firstWonTime;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstWonTime(String firstWonTime) {
    this.firstWonTime = firstWonTime;
  }


  public BaseDeal lostTime(String lostTime) {
    
    this.lostTime = lostTime;
    return this;
  }

   /**
   * The date and time of changing the deal status as lost
   * @return lostTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of changing the deal status as lost")
  @JsonProperty(JSON_PROPERTY_LOST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLostTime() {
    return lostTime;
  }


  @JsonProperty(JSON_PROPERTY_LOST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLostTime(String lostTime) {
    this.lostTime = lostTime;
  }


  public BaseDeal productsCount(Integer productsCount) {
    
    this.productsCount = productsCount;
    return this;
  }

   /**
   * The number of products associated with the deal
   * @return productsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of products associated with the deal")
  @JsonProperty(JSON_PROPERTY_PRODUCTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProductsCount() {
    return productsCount;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductsCount(Integer productsCount) {
    this.productsCount = productsCount;
  }


  public BaseDeal filesCount(Integer filesCount) {
    
    this.filesCount = filesCount;
    return this;
  }

   /**
   * The number of files associated with the deal
   * @return filesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of files associated with the deal")
  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFilesCount() {
    return filesCount;
  }


  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilesCount(Integer filesCount) {
    this.filesCount = filesCount;
  }


  public BaseDeal notesCount(Integer notesCount) {
    
    this.notesCount = notesCount;
    return this;
  }

   /**
   * The number of notes associated with the deal
   * @return notesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of notes associated with the deal")
  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNotesCount() {
    return notesCount;
  }


  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotesCount(Integer notesCount) {
    this.notesCount = notesCount;
  }


  public BaseDeal followersCount(Integer followersCount) {
    
    this.followersCount = followersCount;
    return this;
  }

   /**
   * The number of followers associated with the deal
   * @return followersCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of followers associated with the deal")
  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFollowersCount() {
    return followersCount;
  }


  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowersCount(Integer followersCount) {
    this.followersCount = followersCount;
  }


  public BaseDeal emailMessagesCount(Integer emailMessagesCount) {
    
    this.emailMessagesCount = emailMessagesCount;
    return this;
  }

   /**
   * The number of emails associated with the deal
   * @return emailMessagesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of emails associated with the deal")
  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEmailMessagesCount() {
    return emailMessagesCount;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailMessagesCount(Integer emailMessagesCount) {
    this.emailMessagesCount = emailMessagesCount;
  }


  public BaseDeal activitiesCount(Integer activitiesCount) {
    
    this.activitiesCount = activitiesCount;
    return this;
  }

   /**
   * The number of activities associated with the deal
   * @return activitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivitiesCount() {
    return activitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivitiesCount(Integer activitiesCount) {
    this.activitiesCount = activitiesCount;
  }


  public BaseDeal doneActivitiesCount(Integer doneActivitiesCount) {
    
    this.doneActivitiesCount = doneActivitiesCount;
    return this;
  }

   /**
   * The number of completed activities associated with the deal
   * @return doneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of completed activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDoneActivitiesCount() {
    return doneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneActivitiesCount(Integer doneActivitiesCount) {
    this.doneActivitiesCount = doneActivitiesCount;
  }


  public BaseDeal undoneActivitiesCount(Integer undoneActivitiesCount) {
    
    this.undoneActivitiesCount = undoneActivitiesCount;
    return this;
  }

   /**
   * The number of incomplete activities associated with the deal
   * @return undoneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of incomplete activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUndoneActivitiesCount() {
    return undoneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUndoneActivitiesCount(Integer undoneActivitiesCount) {
    this.undoneActivitiesCount = undoneActivitiesCount;
  }


  public BaseDeal participantsCount(Integer participantsCount) {
    
    this.participantsCount = participantsCount;
    return this;
  }

   /**
   * The number of participants associated with the deal
   * @return participantsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of participants associated with the deal")
  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getParticipantsCount() {
    return participantsCount;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParticipantsCount(Integer participantsCount) {
    this.participantsCount = participantsCount;
  }


  public BaseDeal expectedCloseDate(LocalDate expectedCloseDate) {
    
    this.expectedCloseDate = expectedCloseDate;
    return this;
  }

   /**
   * The expected close date of the deal
   * @return expectedCloseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expected close date of the deal")
  @JsonProperty(JSON_PROPERTY_EXPECTED_CLOSE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getExpectedCloseDate() {
    return expectedCloseDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPECTED_CLOSE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpectedCloseDate(LocalDate expectedCloseDate) {
    this.expectedCloseDate = expectedCloseDate;
  }


  public BaseDeal lastIncomingMailTime(String lastIncomingMailTime) {
    
    this.lastIncomingMailTime = lastIncomingMailTime;
    return this;
  }

   /**
   * The date and time of the last incoming email associated with the deal
   * @return lastIncomingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last incoming email associated with the deal")
  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastIncomingMailTime() {
    return lastIncomingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastIncomingMailTime(String lastIncomingMailTime) {
    this.lastIncomingMailTime = lastIncomingMailTime;
  }


  public BaseDeal lastOutgoingMailTime(String lastOutgoingMailTime) {
    
    this.lastOutgoingMailTime = lastOutgoingMailTime;
    return this;
  }

   /**
   * The date and time of the last outgoing email associated with the deal
   * @return lastOutgoingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last outgoing email associated with the deal")
  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastOutgoingMailTime() {
    return lastOutgoingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastOutgoingMailTime(String lastOutgoingMailTime) {
    this.lastOutgoingMailTime = lastOutgoingMailTime;
  }


  public BaseDeal label(Integer label) {
    
    this.label = label;
    return this;
  }

   /**
   * The label assigned to the deal
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The label assigned to the deal")
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(Integer label) {
    this.label = label;
  }


  public BaseDeal stageOrderNr(Integer stageOrderNr) {
    
    this.stageOrderNr = stageOrderNr;
    return this;
  }

   /**
   * The order number of the deal stage associated with the deal
   * @return stageOrderNr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order number of the deal stage associated with the deal")
  @JsonProperty(JSON_PROPERTY_STAGE_ORDER_NR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStageOrderNr() {
    return stageOrderNr;
  }


  @JsonProperty(JSON_PROPERTY_STAGE_ORDER_NR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStageOrderNr(Integer stageOrderNr) {
    this.stageOrderNr = stageOrderNr;
  }


  public BaseDeal personName(String personName) {
    
    this.personName = personName;
    return this;
  }

   /**
   * The name of the person associated with the deal
   * @return personName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the person associated with the deal")
  @JsonProperty(JSON_PROPERTY_PERSON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPersonName() {
    return personName;
  }


  @JsonProperty(JSON_PROPERTY_PERSON_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonName(String personName) {
    this.personName = personName;
  }


  public BaseDeal orgName(String orgName) {
    
    this.orgName = orgName;
    return this;
  }

   /**
   * The name of the organization associated with the deal
   * @return orgName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the organization associated with the deal")
  @JsonProperty(JSON_PROPERTY_ORG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrgName() {
    return orgName;
  }


  @JsonProperty(JSON_PROPERTY_ORG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


  public BaseDeal nextActivitySubject(String nextActivitySubject) {
    
    this.nextActivitySubject = nextActivitySubject;
    return this;
  }

   /**
   * The subject of the next activity associated with the deal
   * @return nextActivitySubject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The subject of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivitySubject() {
    return nextActivitySubject;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivitySubject(String nextActivitySubject) {
    this.nextActivitySubject = nextActivitySubject;
  }


  public BaseDeal nextActivityType(String nextActivityType) {
    
    this.nextActivityType = nextActivityType;
    return this;
  }

   /**
   * The type of the next activity associated with the deal
   * @return nextActivityType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityType() {
    return nextActivityType;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityType(String nextActivityType) {
    this.nextActivityType = nextActivityType;
  }


  public BaseDeal nextActivityDuration(String nextActivityDuration) {
    
    this.nextActivityDuration = nextActivityDuration;
    return this;
  }

   /**
   * The duration of the next activity associated with the deal
   * @return nextActivityDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The duration of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityDuration() {
    return nextActivityDuration;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityDuration(String nextActivityDuration) {
    this.nextActivityDuration = nextActivityDuration;
  }


  public BaseDeal nextActivityNote(String nextActivityNote) {
    
    this.nextActivityNote = nextActivityNote;
    return this;
  }

   /**
   * The note of the next activity associated with the deal
   * @return nextActivityNote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The note of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityNote() {
    return nextActivityNote;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityNote(String nextActivityNote) {
    this.nextActivityNote = nextActivityNote;
  }


  public BaseDeal formattedValue(String formattedValue) {
    
    this.formattedValue = formattedValue;
    return this;
  }

   /**
   * The deal value formatted with selected currency. E.g. US$500
   * @return formattedValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The deal value formatted with selected currency. E.g. US$500")
  @JsonProperty(JSON_PROPERTY_FORMATTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormattedValue() {
    return formattedValue;
  }


  @JsonProperty(JSON_PROPERTY_FORMATTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormattedValue(String formattedValue) {
    this.formattedValue = formattedValue;
  }


  public BaseDeal weightedValue(BigDecimal weightedValue) {
    
    this.weightedValue = weightedValue;
    return this;
  }

   /**
   * Probability times deal value. Probability can either be deal probability or if not set, then stage probability.
   * @return weightedValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Probability times deal value. Probability can either be deal probability or if not set, then stage probability.")
  @JsonProperty(JSON_PROPERTY_WEIGHTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWeightedValue() {
    return weightedValue;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightedValue(BigDecimal weightedValue) {
    this.weightedValue = weightedValue;
  }


  public BaseDeal formattedWeightedValue(String formattedWeightedValue) {
    
    this.formattedWeightedValue = formattedWeightedValue;
    return this;
  }

   /**
   * The weighted_value formatted with selected currency. E.g. US$500
   * @return formattedWeightedValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The weighted_value formatted with selected currency. E.g. US$500")
  @JsonProperty(JSON_PROPERTY_FORMATTED_WEIGHTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormattedWeightedValue() {
    return formattedWeightedValue;
  }


  @JsonProperty(JSON_PROPERTY_FORMATTED_WEIGHTED_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormattedWeightedValue(String formattedWeightedValue) {
    this.formattedWeightedValue = formattedWeightedValue;
  }


  public BaseDeal weightedValueCurrency(String weightedValueCurrency) {
    
    this.weightedValueCurrency = weightedValueCurrency;
    return this;
  }

   /**
   * The currency associated with the deal
   * @return weightedValueCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The currency associated with the deal")
  @JsonProperty(JSON_PROPERTY_WEIGHTED_VALUE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWeightedValueCurrency() {
    return weightedValueCurrency;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHTED_VALUE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightedValueCurrency(String weightedValueCurrency) {
    this.weightedValueCurrency = weightedValueCurrency;
  }


  public BaseDeal rottenTime(String rottenTime) {
    this.rottenTime = JsonNullable.<String>of(rottenTime);
    
    return this;
  }

   /**
   * The date and time of changing the deal status as rotten
   * @return rottenTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of changing the deal status as rotten")
  @JsonIgnore

  public String getRottenTime() {
        return rottenTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ROTTEN_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getRottenTime_JsonNullable() {
    return rottenTime;
  }
  
  @JsonProperty(JSON_PROPERTY_ROTTEN_TIME)
  public void setRottenTime_JsonNullable(JsonNullable<String> rottenTime) {
    this.rottenTime = rottenTime;
  }

  public void setRottenTime(String rottenTime) {
    this.rottenTime = JsonNullable.<String>of(rottenTime);
  }


  public BaseDeal ownerName(String ownerName) {
    
    this.ownerName = ownerName;
    return this;
  }

   /**
   * The name of the deal owner
   * @return ownerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the deal owner")
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerName() {
    return ownerName;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }


  public BaseDeal ccEmail(String ccEmail) {
    
    this.ccEmail = ccEmail;
    return this;
  }

   /**
   * The BCC email of the deal
   * @return ccEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The BCC email of the deal")
  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCcEmail() {
    return ccEmail;
  }


  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCcEmail(String ccEmail) {
    this.ccEmail = ccEmail;
  }


  public BaseDeal orgHidden(Boolean orgHidden) {
    
    this.orgHidden = orgHidden;
    return this;
  }

   /**
   * If the organization that is associated with the deal is hidden or not
   * @return orgHidden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the organization that is associated with the deal is hidden or not")
  @JsonProperty(JSON_PROPERTY_ORG_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOrgHidden() {
    return orgHidden;
  }


  @JsonProperty(JSON_PROPERTY_ORG_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgHidden(Boolean orgHidden) {
    this.orgHidden = orgHidden;
  }


  public BaseDeal personHidden(Boolean personHidden) {
    
    this.personHidden = personHidden;
    return this;
  }

   /**
   * If the person that is associated with the deal is hidden or not
   * @return personHidden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the person that is associated with the deal is hidden or not")
  @JsonProperty(JSON_PROPERTY_PERSON_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPersonHidden() {
    return personHidden;
  }


  @JsonProperty(JSON_PROPERTY_PERSON_HIDDEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonHidden(Boolean personHidden) {
    this.personHidden = personHidden;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseDeal baseDeal = (BaseDeal) o;
    return Objects.equals(this.stageId, baseDeal.stageId) &&
        Objects.equals(this.title, baseDeal.title) &&
        Objects.equals(this.value, baseDeal.value) &&
        Objects.equals(this.currency, baseDeal.currency) &&
        Objects.equals(this.addTime, baseDeal.addTime) &&
        Objects.equals(this.updateTime, baseDeal.updateTime) &&
        Objects.equals(this.stageChangeTime, baseDeal.stageChangeTime) &&
        Objects.equals(this.active, baseDeal.active) &&
        Objects.equals(this.deleted, baseDeal.deleted) &&
        Objects.equals(this.status, baseDeal.status) &&
        equalsNullable(this.probability, baseDeal.probability) &&
        Objects.equals(this.nextActivityDate, baseDeal.nextActivityDate) &&
        Objects.equals(this.nextActivityTime, baseDeal.nextActivityTime) &&
        equalsNullable(this.nextActivityId, baseDeal.nextActivityId) &&
        equalsNullable(this.lastActivityId, baseDeal.lastActivityId) &&
        equalsNullable(this.lastActivityDate, baseDeal.lastActivityDate) &&
        equalsNullable(this.lostReason, baseDeal.lostReason) &&
        Objects.equals(this.visibleTo, baseDeal.visibleTo) &&
        equalsNullable(this.closeTime, baseDeal.closeTime) &&
        Objects.equals(this.pipelineId, baseDeal.pipelineId) &&
        Objects.equals(this.wonTime, baseDeal.wonTime) &&
        Objects.equals(this.firstWonTime, baseDeal.firstWonTime) &&
        Objects.equals(this.lostTime, baseDeal.lostTime) &&
        Objects.equals(this.productsCount, baseDeal.productsCount) &&
        Objects.equals(this.filesCount, baseDeal.filesCount) &&
        Objects.equals(this.notesCount, baseDeal.notesCount) &&
        Objects.equals(this.followersCount, baseDeal.followersCount) &&
        Objects.equals(this.emailMessagesCount, baseDeal.emailMessagesCount) &&
        Objects.equals(this.activitiesCount, baseDeal.activitiesCount) &&
        Objects.equals(this.doneActivitiesCount, baseDeal.doneActivitiesCount) &&
        Objects.equals(this.undoneActivitiesCount, baseDeal.undoneActivitiesCount) &&
        Objects.equals(this.participantsCount, baseDeal.participantsCount) &&
        Objects.equals(this.expectedCloseDate, baseDeal.expectedCloseDate) &&
        Objects.equals(this.lastIncomingMailTime, baseDeal.lastIncomingMailTime) &&
        Objects.equals(this.lastOutgoingMailTime, baseDeal.lastOutgoingMailTime) &&
        Objects.equals(this.label, baseDeal.label) &&
        Objects.equals(this.stageOrderNr, baseDeal.stageOrderNr) &&
        Objects.equals(this.personName, baseDeal.personName) &&
        Objects.equals(this.orgName, baseDeal.orgName) &&
        Objects.equals(this.nextActivitySubject, baseDeal.nextActivitySubject) &&
        Objects.equals(this.nextActivityType, baseDeal.nextActivityType) &&
        Objects.equals(this.nextActivityDuration, baseDeal.nextActivityDuration) &&
        Objects.equals(this.nextActivityNote, baseDeal.nextActivityNote) &&
        Objects.equals(this.formattedValue, baseDeal.formattedValue) &&
        Objects.equals(this.weightedValue, baseDeal.weightedValue) &&
        Objects.equals(this.formattedWeightedValue, baseDeal.formattedWeightedValue) &&
        Objects.equals(this.weightedValueCurrency, baseDeal.weightedValueCurrency) &&
        equalsNullable(this.rottenTime, baseDeal.rottenTime) &&
        Objects.equals(this.ownerName, baseDeal.ownerName) &&
        Objects.equals(this.ccEmail, baseDeal.ccEmail) &&
        Objects.equals(this.orgHidden, baseDeal.orgHidden) &&
        Objects.equals(this.personHidden, baseDeal.personHidden);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(stageId, title, value, currency, addTime, updateTime, stageChangeTime, active, deleted, status, hashCodeNullable(probability), nextActivityDate, nextActivityTime, hashCodeNullable(nextActivityId), hashCodeNullable(lastActivityId), hashCodeNullable(lastActivityDate), hashCodeNullable(lostReason), visibleTo, hashCodeNullable(closeTime), pipelineId, wonTime, firstWonTime, lostTime, productsCount, filesCount, notesCount, followersCount, emailMessagesCount, activitiesCount, doneActivitiesCount, undoneActivitiesCount, participantsCount, expectedCloseDate, lastIncomingMailTime, lastOutgoingMailTime, label, stageOrderNr, personName, orgName, nextActivitySubject, nextActivityType, nextActivityDuration, nextActivityNote, formattedValue, weightedValue, formattedWeightedValue, weightedValueCurrency, hashCodeNullable(rottenTime), ownerName, ccEmail, orgHidden, personHidden);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseDeal {\n");
    sb.append("    stageId: ").append(toIndentedString(stageId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    stageChangeTime: ").append(toIndentedString(stageChangeTime)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    nextActivityDate: ").append(toIndentedString(nextActivityDate)).append("\n");
    sb.append("    nextActivityTime: ").append(toIndentedString(nextActivityTime)).append("\n");
    sb.append("    nextActivityId: ").append(toIndentedString(nextActivityId)).append("\n");
    sb.append("    lastActivityId: ").append(toIndentedString(lastActivityId)).append("\n");
    sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
    sb.append("    lostReason: ").append(toIndentedString(lostReason)).append("\n");
    sb.append("    visibleTo: ").append(toIndentedString(visibleTo)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    pipelineId: ").append(toIndentedString(pipelineId)).append("\n");
    sb.append("    wonTime: ").append(toIndentedString(wonTime)).append("\n");
    sb.append("    firstWonTime: ").append(toIndentedString(firstWonTime)).append("\n");
    sb.append("    lostTime: ").append(toIndentedString(lostTime)).append("\n");
    sb.append("    productsCount: ").append(toIndentedString(productsCount)).append("\n");
    sb.append("    filesCount: ").append(toIndentedString(filesCount)).append("\n");
    sb.append("    notesCount: ").append(toIndentedString(notesCount)).append("\n");
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    emailMessagesCount: ").append(toIndentedString(emailMessagesCount)).append("\n");
    sb.append("    activitiesCount: ").append(toIndentedString(activitiesCount)).append("\n");
    sb.append("    doneActivitiesCount: ").append(toIndentedString(doneActivitiesCount)).append("\n");
    sb.append("    undoneActivitiesCount: ").append(toIndentedString(undoneActivitiesCount)).append("\n");
    sb.append("    participantsCount: ").append(toIndentedString(participantsCount)).append("\n");
    sb.append("    expectedCloseDate: ").append(toIndentedString(expectedCloseDate)).append("\n");
    sb.append("    lastIncomingMailTime: ").append(toIndentedString(lastIncomingMailTime)).append("\n");
    sb.append("    lastOutgoingMailTime: ").append(toIndentedString(lastOutgoingMailTime)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    stageOrderNr: ").append(toIndentedString(stageOrderNr)).append("\n");
    sb.append("    personName: ").append(toIndentedString(personName)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    nextActivitySubject: ").append(toIndentedString(nextActivitySubject)).append("\n");
    sb.append("    nextActivityType: ").append(toIndentedString(nextActivityType)).append("\n");
    sb.append("    nextActivityDuration: ").append(toIndentedString(nextActivityDuration)).append("\n");
    sb.append("    nextActivityNote: ").append(toIndentedString(nextActivityNote)).append("\n");
    sb.append("    formattedValue: ").append(toIndentedString(formattedValue)).append("\n");
    sb.append("    weightedValue: ").append(toIndentedString(weightedValue)).append("\n");
    sb.append("    formattedWeightedValue: ").append(toIndentedString(formattedWeightedValue)).append("\n");
    sb.append("    weightedValueCurrency: ").append(toIndentedString(weightedValueCurrency)).append("\n");
    sb.append("    rottenTime: ").append(toIndentedString(rottenTime)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    ccEmail: ").append(toIndentedString(ccEmail)).append("\n");
    sb.append("    orgHidden: ").append(toIndentedString(orgHidden)).append("\n");
    sb.append("    personHidden: ").append(toIndentedString(personHidden)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

