/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetAssociatedFollowersResponse2001DataInner
 */
@JsonPropertyOrder({
  GetAssociatedFollowersResponse2001DataInner.JSON_PROPERTY_ORG_ID,
  GetAssociatedFollowersResponse2001DataInner.JSON_PROPERTY_USER_ID,
  GetAssociatedFollowersResponse2001DataInner.JSON_PROPERTY_ID,
  GetAssociatedFollowersResponse2001DataInner.JSON_PROPERTY_ADD_TIME
})
@JsonTypeName("getAssociatedFollowersResponse200_1_data_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetAssociatedFollowersResponse2001DataInner {
  public static final String JSON_PROPERTY_ORG_ID = "org_id";
  private Integer orgId;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private Integer userId;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private OffsetDateTime addTime;

  public GetAssociatedFollowersResponse2001DataInner() {
  }

  public GetAssociatedFollowersResponse2001DataInner orgId(Integer orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * The ID of the organization
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the organization")
  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrgId() {
    return orgId;
  }


  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgId(Integer orgId) {
    this.orgId = orgId;
  }


  public GetAssociatedFollowersResponse2001DataInner userId(Integer userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The user ID of the follower related to the item
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user ID of the follower related to the item")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public GetAssociatedFollowersResponse2001DataInner id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the follower
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the follower")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public GetAssociatedFollowersResponse2001DataInner addTime(OffsetDateTime addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The date and time of adding the follower to the item
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of adding the follower to the item")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(OffsetDateTime addTime) {
    this.addTime = addTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAssociatedFollowersResponse2001DataInner getAssociatedFollowersResponse2001DataInner = (GetAssociatedFollowersResponse2001DataInner) o;
    return Objects.equals(this.orgId, getAssociatedFollowersResponse2001DataInner.orgId) &&
        Objects.equals(this.userId, getAssociatedFollowersResponse2001DataInner.userId) &&
        Objects.equals(this.id, getAssociatedFollowersResponse2001DataInner.id) &&
        Objects.equals(this.addTime, getAssociatedFollowersResponse2001DataInner.addTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orgId, userId, id, addTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAssociatedFollowersResponse2001DataInner {\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

