/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.AddActivityResponse200RelatedObjectsOrganization;
import com.zenika.pipedrive.model.AddActivityResponse200RelatedObjectsPerson;
import com.zenika.pipedrive.model.GetActivitiesResponse200RelatedObjectsUser;
import com.zenika.pipedrive.model.GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline;
import com.zenika.pipedrive.model.GetAssociatedDealsResponse200AllOfRelatedObjectsStage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetAssociatedDealsResponse200AllOfRelatedObjects
 */
@JsonPropertyOrder({
  GetAssociatedDealsResponse200AllOfRelatedObjects.JSON_PROPERTY_ORGANIZATION,
  GetAssociatedDealsResponse200AllOfRelatedObjects.JSON_PROPERTY_PERSON,
  GetAssociatedDealsResponse200AllOfRelatedObjects.JSON_PROPERTY_USER,
  GetAssociatedDealsResponse200AllOfRelatedObjects.JSON_PROPERTY_STAGE,
  GetAssociatedDealsResponse200AllOfRelatedObjects.JSON_PROPERTY_PIPELINE
})
@JsonTypeName("getAssociatedDealsResponse200_allOf_related_objects")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetAssociatedDealsResponse200AllOfRelatedObjects {
  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private AddActivityResponse200RelatedObjectsOrganization organization;

  public static final String JSON_PROPERTY_PERSON = "person";
  private AddActivityResponse200RelatedObjectsPerson person;

  public static final String JSON_PROPERTY_USER = "user";
  private GetActivitiesResponse200RelatedObjectsUser user;

  public static final String JSON_PROPERTY_STAGE = "stage";
  private GetAssociatedDealsResponse200AllOfRelatedObjectsStage stage;

  public static final String JSON_PROPERTY_PIPELINE = "pipeline";
  private GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline pipeline;

  public GetAssociatedDealsResponse200AllOfRelatedObjects() {
  }

  public GetAssociatedDealsResponse200AllOfRelatedObjects organization(AddActivityResponse200RelatedObjectsOrganization organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddActivityResponse200RelatedObjectsOrganization getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(AddActivityResponse200RelatedObjectsOrganization organization) {
    this.organization = organization;
  }


  public GetAssociatedDealsResponse200AllOfRelatedObjects person(AddActivityResponse200RelatedObjectsPerson person) {
    
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddActivityResponse200RelatedObjectsPerson getPerson() {
    return person;
  }


  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerson(AddActivityResponse200RelatedObjectsPerson person) {
    this.person = person;
  }


  public GetAssociatedDealsResponse200AllOfRelatedObjects user(GetActivitiesResponse200RelatedObjectsUser user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetActivitiesResponse200RelatedObjectsUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(GetActivitiesResponse200RelatedObjectsUser user) {
    this.user = user;
  }


  public GetAssociatedDealsResponse200AllOfRelatedObjects stage(GetAssociatedDealsResponse200AllOfRelatedObjectsStage stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAssociatedDealsResponse200AllOfRelatedObjectsStage getStage() {
    return stage;
  }


  @JsonProperty(JSON_PROPERTY_STAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStage(GetAssociatedDealsResponse200AllOfRelatedObjectsStage stage) {
    this.stage = stage;
  }


  public GetAssociatedDealsResponse200AllOfRelatedObjects pipeline(GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline pipeline) {
    
    this.pipeline = pipeline;
    return this;
  }

   /**
   * Get pipeline
   * @return pipeline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PIPELINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline getPipeline() {
    return pipeline;
  }


  @JsonProperty(JSON_PROPERTY_PIPELINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPipeline(GetAssociatedDealsResponse200AllOfRelatedObjectsPipeline pipeline) {
    this.pipeline = pipeline;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAssociatedDealsResponse200AllOfRelatedObjects getAssociatedDealsResponse200AllOfRelatedObjects = (GetAssociatedDealsResponse200AllOfRelatedObjects) o;
    return Objects.equals(this.organization, getAssociatedDealsResponse200AllOfRelatedObjects.organization) &&
        Objects.equals(this.person, getAssociatedDealsResponse200AllOfRelatedObjects.person) &&
        Objects.equals(this.user, getAssociatedDealsResponse200AllOfRelatedObjects.user) &&
        Objects.equals(this.stage, getAssociatedDealsResponse200AllOfRelatedObjects.stage) &&
        Objects.equals(this.pipeline, getAssociatedDealsResponse200AllOfRelatedObjects.pipeline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organization, person, user, stage, pipeline);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAssociatedDealsResponse200AllOfRelatedObjects {\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    pipeline: ").append(toIndentedString(pipeline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

