/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The total values of the deals grouped by deal currency
 */
@ApiModel(description = "The total values of the deals grouped by deal currency")
@JsonPropertyOrder({
  GetDealsSummaryResponse200DataValuesTotal.JSON_PROPERTY_VALUE,
  GetDealsSummaryResponse200DataValuesTotal.JSON_PROPERTY_COUNT,
  GetDealsSummaryResponse200DataValuesTotal.JSON_PROPERTY_VALUE_CONVERTED,
  GetDealsSummaryResponse200DataValuesTotal.JSON_PROPERTY_VALUE_FORMATTED,
  GetDealsSummaryResponse200DataValuesTotal.JSON_PROPERTY_VALUE_CONVERTED_FORMATTED
})
@JsonTypeName("getDealsSummaryResponse200_data_values_total")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetDealsSummaryResponse200DataValuesTotal {
  public static final String JSON_PROPERTY_VALUE = "value";
  private BigDecimal value;

  public static final String JSON_PROPERTY_COUNT = "count";
  private Integer count;

  public static final String JSON_PROPERTY_VALUE_CONVERTED = "value_converted";
  private BigDecimal valueConverted;

  public static final String JSON_PROPERTY_VALUE_FORMATTED = "value_formatted";
  private String valueFormatted;

  public static final String JSON_PROPERTY_VALUE_CONVERTED_FORMATTED = "value_converted_formatted";
  private String valueConvertedFormatted;

  public GetDealsSummaryResponse200DataValuesTotal() {
  }

  public GetDealsSummaryResponse200DataValuesTotal value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * The total value of deals in the deal currency group
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of deals in the deal currency group")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(BigDecimal value) {
    this.value = value;
  }


  public GetDealsSummaryResponse200DataValuesTotal count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * The number of deals in the deal currency group
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of deals in the deal currency group")
  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCount(Integer count) {
    this.count = count;
  }


  public GetDealsSummaryResponse200DataValuesTotal valueConverted(BigDecimal valueConverted) {
    
    this.valueConverted = valueConverted;
    return this;
  }

   /**
   * The total value of deals converted into the company default currency
   * @return valueConverted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of deals converted into the company default currency")
  @JsonProperty(JSON_PROPERTY_VALUE_CONVERTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getValueConverted() {
    return valueConverted;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_CONVERTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueConverted(BigDecimal valueConverted) {
    this.valueConverted = valueConverted;
  }


  public GetDealsSummaryResponse200DataValuesTotal valueFormatted(String valueFormatted) {
    
    this.valueFormatted = valueFormatted;
    return this;
  }

   /**
   * The total value of deals formatted with deal currency. E.g. €50
   * @return valueFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total value of deals formatted with deal currency. E.g. €50")
  @JsonProperty(JSON_PROPERTY_VALUE_FORMATTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueFormatted() {
    return valueFormatted;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_FORMATTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueFormatted(String valueFormatted) {
    this.valueFormatted = valueFormatted;
  }


  public GetDealsSummaryResponse200DataValuesTotal valueConvertedFormatted(String valueConvertedFormatted) {
    
    this.valueConvertedFormatted = valueConvertedFormatted;
    return this;
  }

   /**
   * The value_converted formatted with deal currency. E.g. US$50.10
   * @return valueConvertedFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value_converted formatted with deal currency. E.g. US$50.10")
  @JsonProperty(JSON_PROPERTY_VALUE_CONVERTED_FORMATTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValueConvertedFormatted() {
    return valueConvertedFormatted;
  }


  @JsonProperty(JSON_PROPERTY_VALUE_CONVERTED_FORMATTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueConvertedFormatted(String valueConvertedFormatted) {
    this.valueConvertedFormatted = valueConvertedFormatted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDealsSummaryResponse200DataValuesTotal getDealsSummaryResponse200DataValuesTotal = (GetDealsSummaryResponse200DataValuesTotal) o;
    return Objects.equals(this.value, getDealsSummaryResponse200DataValuesTotal.value) &&
        Objects.equals(this.count, getDealsSummaryResponse200DataValuesTotal.count) &&
        Objects.equals(this.valueConverted, getDealsSummaryResponse200DataValuesTotal.valueConverted) &&
        Objects.equals(this.valueFormatted, getDealsSummaryResponse200DataValuesTotal.valueFormatted) &&
        Objects.equals(this.valueConvertedFormatted, getDealsSummaryResponse200DataValuesTotal.valueConvertedFormatted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, count, valueConverted, valueFormatted, valueConvertedFormatted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDealsSummaryResponse200DataValuesTotal {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    valueConverted: ").append(toIndentedString(valueConverted)).append("\n");
    sb.append("    valueFormatted: ").append(toIndentedString(valueFormatted)).append("\n");
    sb.append("    valueConvertedFormatted: ").append(toIndentedString(valueConvertedFormatted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

