/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.AddActivityResponse200RelatedObjectsPerson;
import com.zenika.pipedrive.model.GetActivitiesResponse200RelatedObjectsDeal;
import com.zenika.pipedrive.model.GetActivitiesResponse200RelatedObjectsOrganization;
import com.zenika.pipedrive.model.GetActivitiesResponse200RelatedObjectsUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetDealUpdatesResponse200AllOfRelatedObjects
 */
@JsonPropertyOrder({
  GetDealUpdatesResponse200AllOfRelatedObjects.JSON_PROPERTY_DEAL,
  GetDealUpdatesResponse200AllOfRelatedObjects.JSON_PROPERTY_ORGANIZATION,
  GetDealUpdatesResponse200AllOfRelatedObjects.JSON_PROPERTY_USER,
  GetDealUpdatesResponse200AllOfRelatedObjects.JSON_PROPERTY_PERSON
})
@JsonTypeName("getDealUpdatesResponse200_allOf_related_objects")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetDealUpdatesResponse200AllOfRelatedObjects {
  public static final String JSON_PROPERTY_DEAL = "deal";
  private GetActivitiesResponse200RelatedObjectsDeal deal;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private GetActivitiesResponse200RelatedObjectsOrganization organization;

  public static final String JSON_PROPERTY_USER = "user";
  private GetActivitiesResponse200RelatedObjectsUser user;

  public static final String JSON_PROPERTY_PERSON = "person";
  private AddActivityResponse200RelatedObjectsPerson person;

  public GetDealUpdatesResponse200AllOfRelatedObjects() {
  }

  public GetDealUpdatesResponse200AllOfRelatedObjects deal(GetActivitiesResponse200RelatedObjectsDeal deal) {
    
    this.deal = deal;
    return this;
  }

   /**
   * Get deal
   * @return deal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetActivitiesResponse200RelatedObjectsDeal getDeal() {
    return deal;
  }


  @JsonProperty(JSON_PROPERTY_DEAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeal(GetActivitiesResponse200RelatedObjectsDeal deal) {
    this.deal = deal;
  }


  public GetDealUpdatesResponse200AllOfRelatedObjects organization(GetActivitiesResponse200RelatedObjectsOrganization organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetActivitiesResponse200RelatedObjectsOrganization getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(GetActivitiesResponse200RelatedObjectsOrganization organization) {
    this.organization = organization;
  }


  public GetDealUpdatesResponse200AllOfRelatedObjects user(GetActivitiesResponse200RelatedObjectsUser user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetActivitiesResponse200RelatedObjectsUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(GetActivitiesResponse200RelatedObjectsUser user) {
    this.user = user;
  }


  public GetDealUpdatesResponse200AllOfRelatedObjects person(AddActivityResponse200RelatedObjectsPerson person) {
    
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddActivityResponse200RelatedObjectsPerson getPerson() {
    return person;
  }


  @JsonProperty(JSON_PROPERTY_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerson(AddActivityResponse200RelatedObjectsPerson person) {
    this.person = person;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDealUpdatesResponse200AllOfRelatedObjects getDealUpdatesResponse200AllOfRelatedObjects = (GetDealUpdatesResponse200AllOfRelatedObjects) o;
    return Objects.equals(this.deal, getDealUpdatesResponse200AllOfRelatedObjects.deal) &&
        Objects.equals(this.organization, getDealUpdatesResponse200AllOfRelatedObjects.organization) &&
        Objects.equals(this.user, getDealUpdatesResponse200AllOfRelatedObjects.user) &&
        Objects.equals(this.person, getDealUpdatesResponse200AllOfRelatedObjects.person);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deal, organization, user, person);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDealUpdatesResponse200AllOfRelatedObjects {\n");
    sb.append("    deal: ").append(toIndentedString(deal)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

