/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.AddOrUpdateGoalResponse200DataGoal;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetGoalResultResponse200Data
 */
@JsonPropertyOrder({
  GetGoalResultResponse200Data.JSON_PROPERTY_PROGRESS,
  GetGoalResultResponse200Data.JSON_PROPERTY_GOAL
})
@JsonTypeName("getGoalResultResponse200_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetGoalResultResponse200Data {
  public static final String JSON_PROPERTY_PROGRESS = "progress";
  private Integer progress;

  public static final String JSON_PROPERTY_GOAL = "goal";
  private AddOrUpdateGoalResponse200DataGoal goal;

  public GetGoalResultResponse200Data() {
  }

  public GetGoalResultResponse200Data progress(Integer progress) {
    
    this.progress = progress;
    return this;
  }

   /**
   * The numeric progress of the goal
   * @return progress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric progress of the goal")
  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProgress() {
    return progress;
  }


  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgress(Integer progress) {
    this.progress = progress;
  }


  public GetGoalResultResponse200Data goal(AddOrUpdateGoalResponse200DataGoal goal) {
    
    this.goal = goal;
    return this;
  }

   /**
   * Get goal
   * @return goal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GOAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddOrUpdateGoalResponse200DataGoal getGoal() {
    return goal;
  }


  @JsonProperty(JSON_PROPERTY_GOAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGoal(AddOrUpdateGoalResponse200DataGoal goal) {
    this.goal = goal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetGoalResultResponse200Data getGoalResultResponse200Data = (GetGoalResultResponse200Data) o;
    return Objects.equals(this.progress, getGoalResultResponse200Data.progress) &&
        Objects.equals(this.goal, getGoalResultResponse200Data.goal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(progress, goal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetGoalResultResponse200Data {\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

