/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetPersonProductsResponse200AllOfDataInnerDEALIDDeal
 */
@JsonPropertyOrder({
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_COMPANY_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_CREATOR_USER_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_USER_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_PERSON_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_ORG_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_STAGE_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_TITLE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_VALUE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_CURRENCY,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_ADD_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_FIRST_ADD_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_UPDATE_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_STAGE_CHANGE_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_ACTIVE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_DELETED,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_STATUS,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_PROBABILITY,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_NEXT_ACTIVITY_DATE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_NEXT_ACTIVITY_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_NEXT_ACTIVITY_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LAST_ACTIVITY_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LAST_ACTIVITY_DATE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LOST_REASON,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_VISIBLE_TO,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_CLOSE_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_PIPELINE_ID,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_WON_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_FIRST_WON_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LOST_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_PRODUCTS_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_FILES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_NOTES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_FOLLOWERS_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_EMAIL_MESSAGES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_ACTIVITIES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_DONE_ACTIVITIES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_PARTICIPANTS_COUNT,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_EXPECTED_CLOSE_DATE,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LAST_INCOMING_MAIL_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME,
  GetPersonProductsResponse200AllOfDataInnerDEALIDDeal.JSON_PROPERTY_LABEL
})
@JsonTypeName("getPersonProductsResponse200_allOf_data_inner_DEAL_ID_deal")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetPersonProductsResponse200AllOfDataInnerDEALIDDeal {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_COMPANY_ID = "company_id";
  private Integer companyId;

  public static final String JSON_PROPERTY_CREATOR_USER_ID = "creator_user_id";
  private Integer creatorUserId;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private Integer userId;

  public static final String JSON_PROPERTY_PERSON_ID = "person_id";
  private Integer personId;

  public static final String JSON_PROPERTY_ORG_ID = "org_id";
  private Integer orgId;

  public static final String JSON_PROPERTY_STAGE_ID = "stage_id";
  private Integer stageId;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_VALUE = "value";
  private BigDecimal value;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private String addTime;

  public static final String JSON_PROPERTY_FIRST_ADD_TIME = "first_add_time";
  private String firstAddTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  private String updateTime;

  public static final String JSON_PROPERTY_STAGE_CHANGE_TIME = "stage_change_time";
  private String stageChangeTime;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_PROBABILITY = "probability";
  private JsonNullable<BigDecimal> probability = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_DATE = "next_activity_date";
  private String nextActivityDate;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_TIME = "next_activity_time";
  private String nextActivityTime;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_ID = "next_activity_id";
  private JsonNullable<Integer> nextActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_ID = "last_activity_id";
  private JsonNullable<Integer> lastActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_DATE = "last_activity_date";
  private JsonNullable<String> lastActivityDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOST_REASON = "lost_reason";
  private JsonNullable<String> lostReason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VISIBLE_TO = "visible_to";
  private String visibleTo;

  public static final String JSON_PROPERTY_CLOSE_TIME = "close_time";
  private JsonNullable<String> closeTime = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PIPELINE_ID = "pipeline_id";
  private Integer pipelineId;

  public static final String JSON_PROPERTY_WON_TIME = "won_time";
  private String wonTime;

  public static final String JSON_PROPERTY_FIRST_WON_TIME = "first_won_time";
  private String firstWonTime;

  public static final String JSON_PROPERTY_LOST_TIME = "lost_time";
  private String lostTime;

  public static final String JSON_PROPERTY_PRODUCTS_COUNT = "products_count";
  private Integer productsCount;

  public static final String JSON_PROPERTY_FILES_COUNT = "files_count";
  private Integer filesCount;

  public static final String JSON_PROPERTY_NOTES_COUNT = "notes_count";
  private Integer notesCount;

  public static final String JSON_PROPERTY_FOLLOWERS_COUNT = "followers_count";
  private Integer followersCount;

  public static final String JSON_PROPERTY_EMAIL_MESSAGES_COUNT = "email_messages_count";
  private Integer emailMessagesCount;

  public static final String JSON_PROPERTY_ACTIVITIES_COUNT = "activities_count";
  private Integer activitiesCount;

  public static final String JSON_PROPERTY_DONE_ACTIVITIES_COUNT = "done_activities_count";
  private Integer doneActivitiesCount;

  public static final String JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT = "undone_activities_count";
  private Integer undoneActivitiesCount;

  public static final String JSON_PROPERTY_PARTICIPANTS_COUNT = "participants_count";
  private Integer participantsCount;

  public static final String JSON_PROPERTY_EXPECTED_CLOSE_DATE = "expected_close_date";
  private LocalDate expectedCloseDate;

  public static final String JSON_PROPERTY_LAST_INCOMING_MAIL_TIME = "last_incoming_mail_time";
  private String lastIncomingMailTime;

  public static final String JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME = "last_outgoing_mail_time";
  private String lastOutgoingMailTime;

  public static final String JSON_PROPERTY_LABEL = "label";
  private String label;

  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal() {
  }

  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the deal
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the deal")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal companyId(Integer companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The ID of the company
   * @return companyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the company")
  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCompanyId() {
    return companyId;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal creatorUserId(Integer creatorUserId) {
    
    this.creatorUserId = creatorUserId;
    return this;
  }

   /**
   * The ID of the deal creator
   * @return creatorUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the deal creator")
  @JsonProperty(JSON_PROPERTY_CREATOR_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCreatorUserId() {
    return creatorUserId;
  }


  @JsonProperty(JSON_PROPERTY_CREATOR_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatorUserId(Integer creatorUserId) {
    this.creatorUserId = creatorUserId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal userId(Integer userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the user")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal personId(Integer personId) {
    
    this.personId = personId;
    return this;
  }

   /**
   * The ID of the person associated with the deal
   * @return personId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the person associated with the deal")
  @JsonProperty(JSON_PROPERTY_PERSON_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPersonId() {
    return personId;
  }


  @JsonProperty(JSON_PROPERTY_PERSON_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonId(Integer personId) {
    this.personId = personId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal orgId(Integer orgId) {
    
    this.orgId = orgId;
    return this;
  }

   /**
   * The ID of the organization associated with the deal
   * @return orgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the organization associated with the deal")
  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOrgId() {
    return orgId;
  }


  @JsonProperty(JSON_PROPERTY_ORG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrgId(Integer orgId) {
    this.orgId = orgId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal stageId(Integer stageId) {
    
    this.stageId = stageId;
    return this;
  }

   /**
   * The ID of the deal stage
   * @return stageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the deal stage")
  @JsonProperty(JSON_PROPERTY_STAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStageId() {
    return stageId;
  }


  @JsonProperty(JSON_PROPERTY_STAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStageId(Integer stageId) {
    this.stageId = stageId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The title of the deal
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The title of the deal")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal value(BigDecimal value) {
    
    this.value = value;
    return this;
  }

   /**
   * The value of the deal
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value of the deal")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(BigDecimal value) {
    this.value = value;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * The currency associated with the deal
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The currency associated with the deal")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The creation date and time of the deal
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The creation date and time of the deal")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal firstAddTime(String firstAddTime) {
    
    this.firstAddTime = firstAddTime;
    return this;
  }

   /**
   * The first creation date and time of the deal
   * @return firstAddTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first creation date and time of the deal")
  @JsonProperty(JSON_PROPERTY_FIRST_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstAddTime() {
    return firstAddTime;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstAddTime(String firstAddTime) {
    this.firstAddTime = firstAddTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The last updated date and time of the deal
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the deal")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal stageChangeTime(String stageChangeTime) {
    
    this.stageChangeTime = stageChangeTime;
    return this;
  }

   /**
   * The last updated date and time of the deal stage
   * @return stageChangeTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the deal stage")
  @JsonProperty(JSON_PROPERTY_STAGE_CHANGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStageChangeTime() {
    return stageChangeTime;
  }


  @JsonProperty(JSON_PROPERTY_STAGE_CHANGE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStageChangeTime(String stageChangeTime) {
    this.stageChangeTime = stageChangeTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Whether the deal is active or not
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the deal is active or not")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Whether the deal is deleted or not
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the deal is deleted or not")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the deal
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of the deal")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal probability(BigDecimal probability) {
    this.probability = JsonNullable.<BigDecimal>of(probability);
    
    return this;
  }

   /**
   * The success probability percentage of the deal
   * @return probability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The success probability percentage of the deal")
  @JsonIgnore

  public BigDecimal getProbability() {
        return probability.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROBABILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getProbability_JsonNullable() {
    return probability;
  }
  
  @JsonProperty(JSON_PROPERTY_PROBABILITY)
  public void setProbability_JsonNullable(JsonNullable<BigDecimal> probability) {
    this.probability = probability;
  }

  public void setProbability(BigDecimal probability) {
    this.probability = JsonNullable.<BigDecimal>of(probability);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal nextActivityDate(String nextActivityDate) {
    
    this.nextActivityDate = nextActivityDate;
    return this;
  }

   /**
   * The date of the next activity associated with the deal
   * @return nextActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityDate() {
    return nextActivityDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityDate(String nextActivityDate) {
    this.nextActivityDate = nextActivityDate;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal nextActivityTime(String nextActivityTime) {
    
    this.nextActivityTime = nextActivityTime;
    return this;
  }

   /**
   * The time of the next activity associated with the deal
   * @return nextActivityTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityTime() {
    return nextActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityTime(String nextActivityTime) {
    this.nextActivityTime = nextActivityTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal nextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
    
    return this;
  }

   /**
   * The ID of the next activity associated with the deal
   * @return nextActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the next activity associated with the deal")
  @JsonIgnore

  public Integer getNextActivityId() {
        return nextActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getNextActivityId_JsonNullable() {
    return nextActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  public void setNextActivityId_JsonNullable(JsonNullable<Integer> nextActivityId) {
    this.nextActivityId = nextActivityId;
  }

  public void setNextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
    
    return this;
  }

   /**
   * The ID of the last activity associated with the deal
   * @return lastActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the last activity associated with the deal")
  @JsonIgnore

  public Integer getLastActivityId() {
        return lastActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLastActivityId_JsonNullable() {
    return lastActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  public void setLastActivityId_JsonNullable(JsonNullable<Integer> lastActivityId) {
    this.lastActivityId = lastActivityId;
  }

  public void setLastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
    
    return this;
  }

   /**
   * The date of the last activity associated with the deal
   * @return lastActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the last activity associated with the deal")
  @JsonIgnore

  public String getLastActivityDate() {
        return lastActivityDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastActivityDate_JsonNullable() {
    return lastActivityDate;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  public void setLastActivityDate_JsonNullable(JsonNullable<String> lastActivityDate) {
    this.lastActivityDate = lastActivityDate;
  }

  public void setLastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lostReason(String lostReason) {
    this.lostReason = JsonNullable.<String>of(lostReason);
    
    return this;
  }

   /**
   * The reason for losing the deal
   * @return lostReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The reason for losing the deal")
  @JsonIgnore

  public String getLostReason() {
        return lostReason.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOST_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLostReason_JsonNullable() {
    return lostReason;
  }
  
  @JsonProperty(JSON_PROPERTY_LOST_REASON)
  public void setLostReason_JsonNullable(JsonNullable<String> lostReason) {
    this.lostReason = lostReason;
  }

  public void setLostReason(String lostReason) {
    this.lostReason = JsonNullable.<String>of(lostReason);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal visibleTo(String visibleTo) {
    
    this.visibleTo = visibleTo;
    return this;
  }

   /**
   * The visibility of the deal
   * @return visibleTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The visibility of the deal")
  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibleTo() {
    return visibleTo;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleTo(String visibleTo) {
    this.visibleTo = visibleTo;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal closeTime(String closeTime) {
    this.closeTime = JsonNullable.<String>of(closeTime);
    
    return this;
  }

   /**
   * The date and time of closing the deal
   * @return closeTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of closing the deal")
  @JsonIgnore

  public String getCloseTime() {
        return closeTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CLOSE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCloseTime_JsonNullable() {
    return closeTime;
  }
  
  @JsonProperty(JSON_PROPERTY_CLOSE_TIME)
  public void setCloseTime_JsonNullable(JsonNullable<String> closeTime) {
    this.closeTime = closeTime;
  }

  public void setCloseTime(String closeTime) {
    this.closeTime = JsonNullable.<String>of(closeTime);
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal pipelineId(Integer pipelineId) {
    
    this.pipelineId = pipelineId;
    return this;
  }

   /**
   * The ID of pipeline associated with the deal
   * @return pipelineId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of pipeline associated with the deal")
  @JsonProperty(JSON_PROPERTY_PIPELINE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPipelineId() {
    return pipelineId;
  }


  @JsonProperty(JSON_PROPERTY_PIPELINE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPipelineId(Integer pipelineId) {
    this.pipelineId = pipelineId;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal wonTime(String wonTime) {
    
    this.wonTime = wonTime;
    return this;
  }

   /**
   * The date and time of changing the deal status as won
   * @return wonTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of changing the deal status as won")
  @JsonProperty(JSON_PROPERTY_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWonTime() {
    return wonTime;
  }


  @JsonProperty(JSON_PROPERTY_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWonTime(String wonTime) {
    this.wonTime = wonTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal firstWonTime(String firstWonTime) {
    
    this.firstWonTime = firstWonTime;
    return this;
  }

   /**
   * The date and time of the first time changing the deal status as won
   * @return firstWonTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the first time changing the deal status as won")
  @JsonProperty(JSON_PROPERTY_FIRST_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstWonTime() {
    return firstWonTime;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_WON_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstWonTime(String firstWonTime) {
    this.firstWonTime = firstWonTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lostTime(String lostTime) {
    
    this.lostTime = lostTime;
    return this;
  }

   /**
   * The date and time of changing the deal status as lost
   * @return lostTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of changing the deal status as lost")
  @JsonProperty(JSON_PROPERTY_LOST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLostTime() {
    return lostTime;
  }


  @JsonProperty(JSON_PROPERTY_LOST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLostTime(String lostTime) {
    this.lostTime = lostTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal productsCount(Integer productsCount) {
    
    this.productsCount = productsCount;
    return this;
  }

   /**
   * The number of products associated with the deal
   * @return productsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of products associated with the deal")
  @JsonProperty(JSON_PROPERTY_PRODUCTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProductsCount() {
    return productsCount;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductsCount(Integer productsCount) {
    this.productsCount = productsCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal filesCount(Integer filesCount) {
    
    this.filesCount = filesCount;
    return this;
  }

   /**
   * The number of files associated with the deal
   * @return filesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of files associated with the deal")
  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFilesCount() {
    return filesCount;
  }


  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilesCount(Integer filesCount) {
    this.filesCount = filesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal notesCount(Integer notesCount) {
    
    this.notesCount = notesCount;
    return this;
  }

   /**
   * The number of notes associated with the deal
   * @return notesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of notes associated with the deal")
  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNotesCount() {
    return notesCount;
  }


  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotesCount(Integer notesCount) {
    this.notesCount = notesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal followersCount(Integer followersCount) {
    
    this.followersCount = followersCount;
    return this;
  }

   /**
   * The number of followers associated with the deal
   * @return followersCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of followers associated with the deal")
  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFollowersCount() {
    return followersCount;
  }


  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowersCount(Integer followersCount) {
    this.followersCount = followersCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal emailMessagesCount(Integer emailMessagesCount) {
    
    this.emailMessagesCount = emailMessagesCount;
    return this;
  }

   /**
   * The number of emails associated with the deal
   * @return emailMessagesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of emails associated with the deal")
  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEmailMessagesCount() {
    return emailMessagesCount;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailMessagesCount(Integer emailMessagesCount) {
    this.emailMessagesCount = emailMessagesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal activitiesCount(Integer activitiesCount) {
    
    this.activitiesCount = activitiesCount;
    return this;
  }

   /**
   * The number of activities associated with the deal
   * @return activitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivitiesCount() {
    return activitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivitiesCount(Integer activitiesCount) {
    this.activitiesCount = activitiesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal doneActivitiesCount(Integer doneActivitiesCount) {
    
    this.doneActivitiesCount = doneActivitiesCount;
    return this;
  }

   /**
   * The number of completed activities associated with the deal
   * @return doneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of completed activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDoneActivitiesCount() {
    return doneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneActivitiesCount(Integer doneActivitiesCount) {
    this.doneActivitiesCount = doneActivitiesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal undoneActivitiesCount(Integer undoneActivitiesCount) {
    
    this.undoneActivitiesCount = undoneActivitiesCount;
    return this;
  }

   /**
   * The number of incomplete activities associated with the deal
   * @return undoneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of incomplete activities associated with the deal")
  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUndoneActivitiesCount() {
    return undoneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUndoneActivitiesCount(Integer undoneActivitiesCount) {
    this.undoneActivitiesCount = undoneActivitiesCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal participantsCount(Integer participantsCount) {
    
    this.participantsCount = participantsCount;
    return this;
  }

   /**
   * The number of participants associated with the deal
   * @return participantsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of participants associated with the deal")
  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getParticipantsCount() {
    return participantsCount;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParticipantsCount(Integer participantsCount) {
    this.participantsCount = participantsCount;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal expectedCloseDate(LocalDate expectedCloseDate) {
    
    this.expectedCloseDate = expectedCloseDate;
    return this;
  }

   /**
   * The expected close date of the deal
   * @return expectedCloseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expected close date of the deal")
  @JsonProperty(JSON_PROPERTY_EXPECTED_CLOSE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getExpectedCloseDate() {
    return expectedCloseDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPECTED_CLOSE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpectedCloseDate(LocalDate expectedCloseDate) {
    this.expectedCloseDate = expectedCloseDate;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lastIncomingMailTime(String lastIncomingMailTime) {
    
    this.lastIncomingMailTime = lastIncomingMailTime;
    return this;
  }

   /**
   * The date and time of the last incoming email associated with the deal
   * @return lastIncomingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last incoming email associated with the deal")
  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastIncomingMailTime() {
    return lastIncomingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_INCOMING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastIncomingMailTime(String lastIncomingMailTime) {
    this.lastIncomingMailTime = lastIncomingMailTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal lastOutgoingMailTime(String lastOutgoingMailTime) {
    
    this.lastOutgoingMailTime = lastOutgoingMailTime;
    return this;
  }

   /**
   * The date and time of the last outgoing email associated with the deal
   * @return lastOutgoingMailTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time of the last outgoing email associated with the deal")
  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastOutgoingMailTime() {
    return lastOutgoingMailTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_OUTGOING_MAIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastOutgoingMailTime(String lastOutgoingMailTime) {
    this.lastOutgoingMailTime = lastOutgoingMailTime;
  }


  public GetPersonProductsResponse200AllOfDataInnerDEALIDDeal label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * The label assigned to the deal
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The label assigned to the deal")
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPersonProductsResponse200AllOfDataInnerDEALIDDeal getPersonProductsResponse200AllOfDataInnerDEALIDDeal = (GetPersonProductsResponse200AllOfDataInnerDEALIDDeal) o;
    return Objects.equals(this.id, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.id) &&
        Objects.equals(this.companyId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.companyId) &&
        Objects.equals(this.creatorUserId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.creatorUserId) &&
        Objects.equals(this.userId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.userId) &&
        Objects.equals(this.personId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.personId) &&
        Objects.equals(this.orgId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.orgId) &&
        Objects.equals(this.stageId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.stageId) &&
        Objects.equals(this.title, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.title) &&
        Objects.equals(this.value, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.value) &&
        Objects.equals(this.currency, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.currency) &&
        Objects.equals(this.addTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.addTime) &&
        Objects.equals(this.firstAddTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.firstAddTime) &&
        Objects.equals(this.updateTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.updateTime) &&
        Objects.equals(this.stageChangeTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.stageChangeTime) &&
        Objects.equals(this.active, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.active) &&
        Objects.equals(this.deleted, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.deleted) &&
        Objects.equals(this.status, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.status) &&
        equalsNullable(this.probability, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.probability) &&
        Objects.equals(this.nextActivityDate, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.nextActivityDate) &&
        Objects.equals(this.nextActivityTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.nextActivityTime) &&
        equalsNullable(this.nextActivityId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.nextActivityId) &&
        equalsNullable(this.lastActivityId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lastActivityId) &&
        equalsNullable(this.lastActivityDate, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lastActivityDate) &&
        equalsNullable(this.lostReason, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lostReason) &&
        Objects.equals(this.visibleTo, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.visibleTo) &&
        equalsNullable(this.closeTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.closeTime) &&
        Objects.equals(this.pipelineId, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.pipelineId) &&
        Objects.equals(this.wonTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.wonTime) &&
        Objects.equals(this.firstWonTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.firstWonTime) &&
        Objects.equals(this.lostTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lostTime) &&
        Objects.equals(this.productsCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.productsCount) &&
        Objects.equals(this.filesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.filesCount) &&
        Objects.equals(this.notesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.notesCount) &&
        Objects.equals(this.followersCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.followersCount) &&
        Objects.equals(this.emailMessagesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.emailMessagesCount) &&
        Objects.equals(this.activitiesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.activitiesCount) &&
        Objects.equals(this.doneActivitiesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.doneActivitiesCount) &&
        Objects.equals(this.undoneActivitiesCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.undoneActivitiesCount) &&
        Objects.equals(this.participantsCount, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.participantsCount) &&
        Objects.equals(this.expectedCloseDate, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.expectedCloseDate) &&
        Objects.equals(this.lastIncomingMailTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lastIncomingMailTime) &&
        Objects.equals(this.lastOutgoingMailTime, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.lastOutgoingMailTime) &&
        Objects.equals(this.label, getPersonProductsResponse200AllOfDataInnerDEALIDDeal.label);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, companyId, creatorUserId, userId, personId, orgId, stageId, title, value, currency, addTime, firstAddTime, updateTime, stageChangeTime, active, deleted, status, hashCodeNullable(probability), nextActivityDate, nextActivityTime, hashCodeNullable(nextActivityId), hashCodeNullable(lastActivityId), hashCodeNullable(lastActivityDate), hashCodeNullable(lostReason), visibleTo, hashCodeNullable(closeTime), pipelineId, wonTime, firstWonTime, lostTime, productsCount, filesCount, notesCount, followersCount, emailMessagesCount, activitiesCount, doneActivitiesCount, undoneActivitiesCount, participantsCount, expectedCloseDate, lastIncomingMailTime, lastOutgoingMailTime, label);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPersonProductsResponse200AllOfDataInnerDEALIDDeal {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    creatorUserId: ").append(toIndentedString(creatorUserId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    stageId: ").append(toIndentedString(stageId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("    firstAddTime: ").append(toIndentedString(firstAddTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    stageChangeTime: ").append(toIndentedString(stageChangeTime)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    nextActivityDate: ").append(toIndentedString(nextActivityDate)).append("\n");
    sb.append("    nextActivityTime: ").append(toIndentedString(nextActivityTime)).append("\n");
    sb.append("    nextActivityId: ").append(toIndentedString(nextActivityId)).append("\n");
    sb.append("    lastActivityId: ").append(toIndentedString(lastActivityId)).append("\n");
    sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
    sb.append("    lostReason: ").append(toIndentedString(lostReason)).append("\n");
    sb.append("    visibleTo: ").append(toIndentedString(visibleTo)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    pipelineId: ").append(toIndentedString(pipelineId)).append("\n");
    sb.append("    wonTime: ").append(toIndentedString(wonTime)).append("\n");
    sb.append("    firstWonTime: ").append(toIndentedString(firstWonTime)).append("\n");
    sb.append("    lostTime: ").append(toIndentedString(lostTime)).append("\n");
    sb.append("    productsCount: ").append(toIndentedString(productsCount)).append("\n");
    sb.append("    filesCount: ").append(toIndentedString(filesCount)).append("\n");
    sb.append("    notesCount: ").append(toIndentedString(notesCount)).append("\n");
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    emailMessagesCount: ").append(toIndentedString(emailMessagesCount)).append("\n");
    sb.append("    activitiesCount: ").append(toIndentedString(activitiesCount)).append("\n");
    sb.append("    doneActivitiesCount: ").append(toIndentedString(doneActivitiesCount)).append("\n");
    sb.append("    undoneActivitiesCount: ").append(toIndentedString(undoneActivitiesCount)).append("\n");
    sb.append("    participantsCount: ").append(toIndentedString(participantsCount)).append("\n");
    sb.append("    expectedCloseDate: ").append(toIndentedString(expectedCloseDate)).append("\n");
    sb.append("    lastIncomingMailTime: ").append(toIndentedString(lastIncomingMailTime)).append("\n");
    sb.append("    lastOutgoingMailTime: ").append(toIndentedString(lastOutgoingMailTime)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

