/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetproductResponse200Data
 */
@JsonPropertyOrder({
  GetproductResponse200Data.JSON_PROPERTY_ID,
  GetproductResponse200Data.JSON_PROPERTY_NAME,
  GetproductResponse200Data.JSON_PROPERTY_CODE,
  GetproductResponse200Data.JSON_PROPERTY_UNIT,
  GetproductResponse200Data.JSON_PROPERTY_TAX,
  GetproductResponse200Data.JSON_PROPERTY_ACTIVE_FLAG,
  GetproductResponse200Data.JSON_PROPERTY_SELECTABLE,
  GetproductResponse200Data.JSON_PROPERTY_VISIBLE_TO,
  GetproductResponse200Data.JSON_PROPERTY_OWNER_ID,
  GetproductResponse200Data.JSON_PROPERTY_PRICES
})
@JsonTypeName("getproductResponse200_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class GetproductResponse200Data {
  public static final String JSON_PROPERTY_ID = "id";
  private BigDecimal id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_UNIT = "unit";
  private String unit;

  public static final String JSON_PROPERTY_TAX = "tax";
  private BigDecimal tax = new BigDecimal("0");

  /**
   * Whether this product is active or not
   */
  public enum ActiveFlagEnum {
    NUMBER_0(new BigDecimal("0")),
    
    NUMBER_1(new BigDecimal("1"));

    private BigDecimal value;

    ActiveFlagEnum(BigDecimal value) {
      this.value = value;
    }

    @JsonValue
    public BigDecimal getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActiveFlagEnum fromValue(BigDecimal value) {
      for (ActiveFlagEnum b : ActiveFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTIVE_FLAG = "active_flag";
  private ActiveFlagEnum activeFlag = ActiveFlagEnum.NUMBER_1;

  /**
   * Whether this product is selected in deals or not
   */
  public enum SelectableEnum {
    NUMBER_0(new BigDecimal("0")),
    
    NUMBER_1(new BigDecimal("1"));

    private BigDecimal value;

    SelectableEnum(BigDecimal value) {
      this.value = value;
    }

    @JsonValue
    public BigDecimal getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SelectableEnum fromValue(BigDecimal value) {
      for (SelectableEnum b : SelectableEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SELECTABLE = "selectable";
  private SelectableEnum selectable = SelectableEnum.NUMBER_1;

  /**
   * Gets or Sets visibleTo
   */
  public enum VisibleToEnum {
    _1("1"),
    
    _3("3"),
    
    _5("5"),
    
    _7("7");

    private String value;

    VisibleToEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VisibleToEnum fromValue(String value) {
      for (VisibleToEnum b : VisibleToEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VISIBLE_TO = "visible_to";
  private VisibleToEnum visibleTo;

  public static final String JSON_PROPERTY_OWNER_ID = "owner_id";
  private Object ownerId;

  public static final String JSON_PROPERTY_PRICES = "prices";
  private List<Object> prices = null;

  public GetproductResponse200Data() {
  }

  public GetproductResponse200Data id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the product
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the product")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(BigDecimal id) {
    this.id = id;
  }


  public GetproductResponse200Data name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the product
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the product")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GetproductResponse200Data code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The product code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The product code")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public GetproductResponse200Data unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * The unit in which this product is sold
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unit in which this product is sold")
  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnit() {
    return unit;
  }


  @JsonProperty(JSON_PROPERTY_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnit(String unit) {
    this.unit = unit;
  }


  public GetproductResponse200Data tax(BigDecimal tax) {
    
    this.tax = tax;
    return this;
  }

   /**
   * The ax percentage
   * @return tax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ax percentage")
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTax() {
    return tax;
  }


  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTax(BigDecimal tax) {
    this.tax = tax;
  }


  public GetproductResponse200Data activeFlag(ActiveFlagEnum activeFlag) {
    
    this.activeFlag = activeFlag;
    return this;
  }

   /**
   * Whether this product is active or not
   * @return activeFlag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this product is active or not")
  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActiveFlagEnum getActiveFlag() {
    return activeFlag;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveFlag(ActiveFlagEnum activeFlag) {
    this.activeFlag = activeFlag;
  }


  public GetproductResponse200Data selectable(SelectableEnum selectable) {
    
    this.selectable = selectable;
    return this;
  }

   /**
   * Whether this product is selected in deals or not
   * @return selectable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether this product is selected in deals or not")
  @JsonProperty(JSON_PROPERTY_SELECTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SelectableEnum getSelectable() {
    return selectable;
  }


  @JsonProperty(JSON_PROPERTY_SELECTABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelectable(SelectableEnum selectable) {
    this.selectable = selectable;
  }


  public GetproductResponse200Data visibleTo(VisibleToEnum visibleTo) {
    
    this.visibleTo = visibleTo;
    return this;
  }

   /**
   * Get visibleTo
   * @return visibleTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VisibleToEnum getVisibleTo() {
    return visibleTo;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleTo(VisibleToEnum visibleTo) {
    this.visibleTo = visibleTo;
  }


  public GetproductResponse200Data ownerId(Object ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Information about the Pipedrive user who owns the product
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Information about the Pipedrive user who owns the product")
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getOwnerId() {
    return ownerId;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerId(Object ownerId) {
    this.ownerId = ownerId;
  }


  public GetproductResponse200Data prices(List<Object> prices) {
    
    this.prices = prices;
    return this;
  }

  public GetproductResponse200Data addPricesItem(Object pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<>();
    }
    this.prices.add(pricesItem);
    return this;
  }

   /**
   * Array of objects, each containing: currency (string), price (number), cost (number, optional), overhead_cost (number, optional)
   * @return prices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Array of objects, each containing: currency (string), price (number), cost (number, optional), overhead_cost (number, optional)")
  @JsonProperty(JSON_PROPERTY_PRICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getPrices() {
    return prices;
  }


  @JsonProperty(JSON_PROPERTY_PRICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrices(List<Object> prices) {
    this.prices = prices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetproductResponse200Data getproductResponse200Data = (GetproductResponse200Data) o;
    return Objects.equals(this.id, getproductResponse200Data.id) &&
        Objects.equals(this.name, getproductResponse200Data.name) &&
        Objects.equals(this.code, getproductResponse200Data.code) &&
        Objects.equals(this.unit, getproductResponse200Data.unit) &&
        Objects.equals(this.tax, getproductResponse200Data.tax) &&
        Objects.equals(this.activeFlag, getproductResponse200Data.activeFlag) &&
        Objects.equals(this.selectable, getproductResponse200Data.selectable) &&
        Objects.equals(this.visibleTo, getproductResponse200Data.visibleTo) &&
        Objects.equals(this.ownerId, getproductResponse200Data.ownerId) &&
        Objects.equals(this.prices, getproductResponse200Data.prices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, code, unit, tax, activeFlag, selectable, visibleTo, ownerId, prices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetproductResponse200Data {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    activeFlag: ").append(toIndentedString(activeFlag)).append("\n");
    sb.append("    selectable: ").append(toIndentedString(selectable)).append("\n");
    sb.append("    visibleTo: ").append(toIndentedString(visibleTo)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

