/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.AddActivityResponse200RelatedObjectsOrganization;
import com.zenika.pipedrive.model.GetActivitiesResponse200RelatedObjectsUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ListPersonsResponse200AllOfRelatedObjects
 */
@JsonPropertyOrder({
  ListPersonsResponse200AllOfRelatedObjects.JSON_PROPERTY_ORGANIZATION,
  ListPersonsResponse200AllOfRelatedObjects.JSON_PROPERTY_USER
})
@JsonTypeName("listPersonsResponse200_allOf_related_objects")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class ListPersonsResponse200AllOfRelatedObjects {
  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private AddActivityResponse200RelatedObjectsOrganization organization;

  public static final String JSON_PROPERTY_USER = "user";
  private GetActivitiesResponse200RelatedObjectsUser user;

  public ListPersonsResponse200AllOfRelatedObjects() {
  }

  public ListPersonsResponse200AllOfRelatedObjects organization(AddActivityResponse200RelatedObjectsOrganization organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddActivityResponse200RelatedObjectsOrganization getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(AddActivityResponse200RelatedObjectsOrganization organization) {
    this.organization = organization;
  }


  public ListPersonsResponse200AllOfRelatedObjects user(GetActivitiesResponse200RelatedObjectsUser user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetActivitiesResponse200RelatedObjectsUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(GetActivitiesResponse200RelatedObjectsUser user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListPersonsResponse200AllOfRelatedObjects listPersonsResponse200AllOfRelatedObjects = (ListPersonsResponse200AllOfRelatedObjects) o;
    return Objects.equals(this.organization, listPersonsResponse200AllOfRelatedObjects.organization) &&
        Objects.equals(this.user, listPersonsResponse200AllOfRelatedObjects.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organization, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListPersonsResponse200AllOfRelatedObjects {\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

