/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NewFollowerResponse200Data
 */
@JsonPropertyOrder({
  NewFollowerResponse200Data.JSON_PROPERTY_USER_ID,
  NewFollowerResponse200Data.JSON_PROPERTY_ID,
  NewFollowerResponse200Data.JSON_PROPERTY_PRODUCT_ID,
  NewFollowerResponse200Data.JSON_PROPERTY_ADD_TIME
})
@JsonTypeName("newFollowerResponse200_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class NewFollowerResponse200Data {
  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private Integer userId;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  private Integer productId;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private String addTime;

  public NewFollowerResponse200Data() {
  }

  public NewFollowerResponse200Data userId(Integer userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user that was added as follower
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the user that was added as follower")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  public NewFollowerResponse200Data id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the follower
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the follower")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public NewFollowerResponse200Data productId(Integer productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * The ID of the product
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the product")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(Integer productId) {
    this.productId = productId;
  }


  public NewFollowerResponse200Data addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The follower creation time. Format: YYYY-MM-DD HH:MM:SS
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The follower creation time. Format: YYYY-MM-DD HH:MM:SS")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewFollowerResponse200Data newFollowerResponse200Data = (NewFollowerResponse200Data) o;
    return Objects.equals(this.userId, newFollowerResponse200Data.userId) &&
        Objects.equals(this.id, newFollowerResponse200Data.id) &&
        Objects.equals(this.productId, newFollowerResponse200Data.productId) &&
        Objects.equals(this.addTime, newFollowerResponse200Data.addTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, id, productId, addTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewFollowerResponse200Data {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

