/*
 * Pipedrive API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zenika.pipedrive.model;

import java.util.HashMap;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zenika.pipedrive.model.BaseOrganizationItemAllOfPictureId;
import com.zenika.pipedrive.model.Owner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OrganizationItem
 */
@JsonPropertyOrder({
  OrganizationItem.JSON_PROPERTY_ID,
  OrganizationItem.JSON_PROPERTY_COMPANY_ID,
  OrganizationItem.JSON_PROPERTY_OWNER_ID,
  OrganizationItem.JSON_PROPERTY_NAME,
  OrganizationItem.JSON_PROPERTY_ACTIVE_FLAG,
  OrganizationItem.JSON_PROPERTY_PICTURE_ID,
  OrganizationItem.JSON_PROPERTY_COUNTRY_CODE,
  OrganizationItem.JSON_PROPERTY_FIRST_CHAR,
  OrganizationItem.JSON_PROPERTY_ADD_TIME,
  OrganizationItem.JSON_PROPERTY_UPDATE_TIME,
  OrganizationItem.JSON_PROPERTY_VISIBLE_TO,
  OrganizationItem.JSON_PROPERTY_LABEL,
  OrganizationItem.JSON_PROPERTY_OWNER_NAME,
  OrganizationItem.JSON_PROPERTY_CC_EMAIL,
  OrganizationItem.JSON_PROPERTY_EMAIL_MESSAGES_COUNT,
  OrganizationItem.JSON_PROPERTY_PEOPLE_COUNT,
  OrganizationItem.JSON_PROPERTY_ACTIVITIES_COUNT,
  OrganizationItem.JSON_PROPERTY_DONE_ACTIVITIES_COUNT,
  OrganizationItem.JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT,
  OrganizationItem.JSON_PROPERTY_FILES_COUNT,
  OrganizationItem.JSON_PROPERTY_NOTES_COUNT,
  OrganizationItem.JSON_PROPERTY_FOLLOWERS_COUNT,
  OrganizationItem.JSON_PROPERTY_ADDRESS,
  OrganizationItem.JSON_PROPERTY_ADDRESS_SUBPREMISE,
  OrganizationItem.JSON_PROPERTY_ADDRESS_STREET_NUMBER,
  OrganizationItem.JSON_PROPERTY_ADDRESS_ROUTE,
  OrganizationItem.JSON_PROPERTY_ADDRESS_SUBLOCALITY,
  OrganizationItem.JSON_PROPERTY_ADDRESS_LOCALITY,
  OrganizationItem.JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL1,
  OrganizationItem.JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL2,
  OrganizationItem.JSON_PROPERTY_ADDRESS_COUNTRY,
  OrganizationItem.JSON_PROPERTY_ADDRESS_POSTAL_CODE,
  OrganizationItem.JSON_PROPERTY_ADDRESS_FORMATTED_ADDRESS,
  OrganizationItem.JSON_PROPERTY_OPEN_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_CLOSED_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_WON_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_RELATED_WON_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_LOST_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_RELATED_LOST_DEALS_COUNT,
  OrganizationItem.JSON_PROPERTY_NEXT_ACTIVITY_DATE,
  OrganizationItem.JSON_PROPERTY_NEXT_ACTIVITY_TIME,
  OrganizationItem.JSON_PROPERTY_NEXT_ACTIVITY_ID,
  OrganizationItem.JSON_PROPERTY_LAST_ACTIVITY_ID,
  OrganizationItem.JSON_PROPERTY_LAST_ACTIVITY_DATE,
  OrganizationItem.JSON_PROPERTY_EDIT_NAME,
  OrganizationItem.JSON_PROPERTY_LAST_ACTIVITY,
  OrganizationItem.JSON_PROPERTY_NEXT_ACTIVITY
})
@JsonTypeName("organizationItem")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-24T19:04:25.918485+01:00[Europe/Paris]")
public class OrganizationItem {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_COMPANY_ID = "company_id";

  public static final String JSON_ACCOUNT_MANAGER = "e3605a045b0a8f245ba8f39aa040984fa136a6fb";
  private HashMap<String, String> accountManager;

  //
  public static final String JSON_COMMERCIAL_TRAINING = "65ce8ba3355440b46602fd510c9d0eaedd441be7";
  private HashMap<String, String> commercialTraining;

  public static final String JSON_PORTFOLIO = "39fa372d6bd7a72582610dc42f63ece2a5386522";

  private HashMap<String, String> portfolio;
  public void setPortfolio(HashMap<String, String> portfolio) {
    this.portfolio = portfolio;
  }

  public HashMap<String, String> getPortfolio() {
    return portfolio;
  }

  public HashMap<String, String> getCommercialTraining() {
    return commercialTraining;
  }

  public void setCommercialTraining(HashMap<String, String> commercialTraining) {
    this.commercialTraining = commercialTraining;
  }

  public HashMap<String, String> getAccountManager() {
    return accountManager;
  }

  public void setAccountManager(HashMap<String, String> accountManager) {
    this.accountManager = accountManager;
  }

  private Integer companyId;

  public static final String JSON_PROPERTY_OWNER_ID = "owner_id";
  private Owner ownerId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ACTIVE_FLAG = "active_flag";
  private Boolean activeFlag;

  public static final String JSON_PROPERTY_PICTURE_ID = "picture_id";
  private BaseOrganizationItemAllOfPictureId pictureId;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  private String countryCode;

  public static final String JSON_PROPERTY_FIRST_CHAR = "first_char";
  private String firstChar;

  public static final String JSON_PROPERTY_ADD_TIME = "add_time";
  private String addTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update_time";
  private String updateTime;

  public static final String JSON_PROPERTY_VISIBLE_TO = "visible_to";
  private String visibleTo;

  public static final String JSON_PROPERTY_LABEL = "label";
  private Integer label;

  public static final String JSON_PROPERTY_OWNER_NAME = "owner_name";
  private String ownerName;

  public static final String JSON_PROPERTY_CC_EMAIL = "cc_email";
  private String ccEmail;

  public static final String JSON_PROPERTY_EMAIL_MESSAGES_COUNT = "email_messages_count";
  private Integer emailMessagesCount;

  public static final String JSON_PROPERTY_PEOPLE_COUNT = "people_count";
  private Integer peopleCount;

  public static final String JSON_PROPERTY_ACTIVITIES_COUNT = "activities_count";
  private Integer activitiesCount;

  public static final String JSON_PROPERTY_DONE_ACTIVITIES_COUNT = "done_activities_count";
  private Integer doneActivitiesCount;

  public static final String JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT = "undone_activities_count";
  private Integer undoneActivitiesCount;

  public static final String JSON_PROPERTY_FILES_COUNT = "files_count";
  private Integer filesCount;

  public static final String JSON_PROPERTY_NOTES_COUNT = "notes_count";
  private Integer notesCount;

  public static final String JSON_PROPERTY_FOLLOWERS_COUNT = "followers_count";
  private Integer followersCount;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_ADDRESS_SUBPREMISE = "address_subpremise";
  private String addressSubpremise;

  public static final String JSON_PROPERTY_ADDRESS_STREET_NUMBER = "address_street_number";
  private String addressStreetNumber;

  public static final String JSON_PROPERTY_ADDRESS_ROUTE = "address_route";
  private String addressRoute;

  public static final String JSON_PROPERTY_ADDRESS_SUBLOCALITY = "address_sublocality";
  private String addressSublocality;

  public static final String JSON_PROPERTY_ADDRESS_LOCALITY = "address_locality";
  private String addressLocality;

  public static final String JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL1 = "address_admin_area_level_1";
  private String addressAdminAreaLevel1;

  public static final String JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL2 = "address_admin_area_level_2";
  private String addressAdminAreaLevel2;

  public static final String JSON_PROPERTY_ADDRESS_COUNTRY = "address_country";
  private String addressCountry;

  public static final String JSON_PROPERTY_ADDRESS_POSTAL_CODE = "address_postal_code";
  private String addressPostalCode;

  public static final String JSON_PROPERTY_ADDRESS_FORMATTED_ADDRESS = "address_formatted_address";
  private String addressFormattedAddress;

  public static final String JSON_PROPERTY_OPEN_DEALS_COUNT = "open_deals_count";
  private Integer openDealsCount;

  public static final String JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT = "related_open_deals_count";
  private Integer relatedOpenDealsCount;

  public static final String JSON_PROPERTY_CLOSED_DEALS_COUNT = "closed_deals_count";
  private Integer closedDealsCount;

  public static final String JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT = "related_closed_deals_count";
  private Integer relatedClosedDealsCount;

  public static final String JSON_PROPERTY_WON_DEALS_COUNT = "won_deals_count";
  private Integer wonDealsCount;

  public static final String JSON_PROPERTY_RELATED_WON_DEALS_COUNT = "related_won_deals_count";
  private Integer relatedWonDealsCount;

  public static final String JSON_PROPERTY_LOST_DEALS_COUNT = "lost_deals_count";
  private Integer lostDealsCount;

  public static final String JSON_PROPERTY_RELATED_LOST_DEALS_COUNT = "related_lost_deals_count";
  private Integer relatedLostDealsCount;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_DATE = "next_activity_date";
  private String nextActivityDate;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_TIME = "next_activity_time";
  private String nextActivityTime;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY_ID = "next_activity_id";
  private JsonNullable<Integer> nextActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_ID = "last_activity_id";
  private JsonNullable<Integer> lastActivityId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_LAST_ACTIVITY_DATE = "last_activity_date";
  private JsonNullable<String> lastActivityDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EDIT_NAME = "edit_name";
  private Boolean editName;

  public static final String JSON_PROPERTY_LAST_ACTIVITY = "last_activity";
  private Object lastActivity;

  public static final String JSON_PROPERTY_NEXT_ACTIVITY = "next_activity";
  private Object nextActivity;

  public OrganizationItem() {
  }

  public OrganizationItem id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the organization
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the organization")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public OrganizationItem companyId(Integer companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The ID of the company related to the organization
   * @return companyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the company related to the organization")
  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCompanyId() {
    return companyId;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }


  public OrganizationItem ownerId(Owner ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Owner getOwnerId() {
    return ownerId;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerId(Owner ownerId) {
    this.ownerId = ownerId;
  }


  public OrganizationItem name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the organization
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the organization")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public OrganizationItem activeFlag(Boolean activeFlag) {
    
    this.activeFlag = activeFlag;
    return this;
  }

   /**
   * Whether the organization is active or not
   * @return activeFlag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether the organization is active or not")
  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActiveFlag() {
    return activeFlag;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveFlag(Boolean activeFlag) {
    this.activeFlag = activeFlag;
  }


  public OrganizationItem pictureId(BaseOrganizationItemAllOfPictureId pictureId) {
    
    this.pictureId = pictureId;
    return this;
  }

   /**
   * Get pictureId
   * @return pictureId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PICTURE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BaseOrganizationItemAllOfPictureId getPictureId() {
    return pictureId;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPictureId(BaseOrganizationItemAllOfPictureId pictureId) {
    this.pictureId = pictureId;
  }


  public OrganizationItem countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country code of the organization
   * @return countryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country code of the organization")
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public OrganizationItem firstChar(String firstChar) {
    
    this.firstChar = firstChar;
    return this;
  }

   /**
   * The first character of the organization name
   * @return firstChar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first character of the organization name")
  @JsonProperty(JSON_PROPERTY_FIRST_CHAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstChar() {
    return firstChar;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_CHAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstChar(String firstChar) {
    this.firstChar = firstChar;
  }


  public OrganizationItem addTime(String addTime) {
    
    this.addTime = addTime;
    return this;
  }

   /**
   * The creation date and time of the organization
   * @return addTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The creation date and time of the organization")
  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddTime() {
    return addTime;
  }


  @JsonProperty(JSON_PROPERTY_ADD_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }


  public OrganizationItem updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * The last updated date and time of the organization
   * @return updateTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last updated date and time of the organization")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public OrganizationItem visibleTo(String visibleTo) {
    
    this.visibleTo = visibleTo;
    return this;
  }

   /**
   * The visibility group ID of who can see the organization
   * @return visibleTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The visibility group ID of who can see the organization")
  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibleTo() {
    return visibleTo;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleTo(String visibleTo) {
    this.visibleTo = visibleTo;
  }


  public OrganizationItem label(Integer label) {
    
    this.label = label;
    return this;
  }

   /**
   * The ID of the label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the label")
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(Integer label) {
    this.label = label;
  }


  public OrganizationItem ownerName(String ownerName) {
    
    this.ownerName = ownerName;
    return this;
  }

   /**
   * The name of the organization owner
   * @return ownerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the organization owner")
  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerName() {
    return ownerName;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }


  public OrganizationItem ccEmail(String ccEmail) {
    
    this.ccEmail = ccEmail;
    return this;
  }

   /**
   * The BCC email of the organization
   * @return ccEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The BCC email of the organization")
  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCcEmail() {
    return ccEmail;
  }


  @JsonProperty(JSON_PROPERTY_CC_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCcEmail(String ccEmail) {
    this.ccEmail = ccEmail;
  }


  public OrganizationItem emailMessagesCount(Integer emailMessagesCount) {
    
    this.emailMessagesCount = emailMessagesCount;
    return this;
  }

   /**
   * The count of email messages related to the organization
   * @return emailMessagesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of email messages related to the organization")
  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEmailMessagesCount() {
    return emailMessagesCount;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_MESSAGES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailMessagesCount(Integer emailMessagesCount) {
    this.emailMessagesCount = emailMessagesCount;
  }


  public OrganizationItem peopleCount(Integer peopleCount) {
    
    this.peopleCount = peopleCount;
    return this;
  }

   /**
   * The count of persons related to the organization
   * @return peopleCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of persons related to the organization")
  @JsonProperty(JSON_PROPERTY_PEOPLE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPeopleCount() {
    return peopleCount;
  }


  @JsonProperty(JSON_PROPERTY_PEOPLE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeopleCount(Integer peopleCount) {
    this.peopleCount = peopleCount;
  }


  public OrganizationItem activitiesCount(Integer activitiesCount) {
    
    this.activitiesCount = activitiesCount;
    return this;
  }

   /**
   * The count of activities related to the organization
   * @return activitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of activities related to the organization")
  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivitiesCount() {
    return activitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivitiesCount(Integer activitiesCount) {
    this.activitiesCount = activitiesCount;
  }


  public OrganizationItem doneActivitiesCount(Integer doneActivitiesCount) {
    
    this.doneActivitiesCount = doneActivitiesCount;
    return this;
  }

   /**
   * The count of done activities related to the organization
   * @return doneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of done activities related to the organization")
  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDoneActivitiesCount() {
    return doneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_DONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneActivitiesCount(Integer doneActivitiesCount) {
    this.doneActivitiesCount = doneActivitiesCount;
  }


  public OrganizationItem undoneActivitiesCount(Integer undoneActivitiesCount) {
    
    this.undoneActivitiesCount = undoneActivitiesCount;
    return this;
  }

   /**
   * The count of undone activities related to the organization
   * @return undoneActivitiesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of undone activities related to the organization")
  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUndoneActivitiesCount() {
    return undoneActivitiesCount;
  }


  @JsonProperty(JSON_PROPERTY_UNDONE_ACTIVITIES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUndoneActivitiesCount(Integer undoneActivitiesCount) {
    this.undoneActivitiesCount = undoneActivitiesCount;
  }


  public OrganizationItem filesCount(Integer filesCount) {
    
    this.filesCount = filesCount;
    return this;
  }

   /**
   * The count of files related to the organization
   * @return filesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of files related to the organization")
  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFilesCount() {
    return filesCount;
  }


  @JsonProperty(JSON_PROPERTY_FILES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilesCount(Integer filesCount) {
    this.filesCount = filesCount;
  }


  public OrganizationItem notesCount(Integer notesCount) {
    
    this.notesCount = notesCount;
    return this;
  }

   /**
   * The count of notes related to the organization
   * @return notesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of notes related to the organization")
  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNotesCount() {
    return notesCount;
  }


  @JsonProperty(JSON_PROPERTY_NOTES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotesCount(Integer notesCount) {
    this.notesCount = notesCount;
  }


  public OrganizationItem followersCount(Integer followersCount) {
    
    this.followersCount = followersCount;
    return this;
  }

   /**
   * The count of followers related to the organization
   * @return followersCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of followers related to the organization")
  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFollowersCount() {
    return followersCount;
  }


  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowersCount(Integer followersCount) {
    this.followersCount = followersCount;
  }


  public OrganizationItem address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * The full address of the organization
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The full address of the organization")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(String address) {
    this.address = address;
  }


  public OrganizationItem addressSubpremise(String addressSubpremise) {
    
    this.addressSubpremise = addressSubpremise;
    return this;
  }

   /**
   * The sub-premise of the organization location
   * @return addressSubpremise
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The sub-premise of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_SUBPREMISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressSubpremise() {
    return addressSubpremise;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_SUBPREMISE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressSubpremise(String addressSubpremise) {
    this.addressSubpremise = addressSubpremise;
  }


  public OrganizationItem addressStreetNumber(String addressStreetNumber) {
    
    this.addressStreetNumber = addressStreetNumber;
    return this;
  }

   /**
   * The street number of the organization location
   * @return addressStreetNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The street number of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_STREET_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressStreetNumber() {
    return addressStreetNumber;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_STREET_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressStreetNumber(String addressStreetNumber) {
    this.addressStreetNumber = addressStreetNumber;
  }


  public OrganizationItem addressRoute(String addressRoute) {
    
    this.addressRoute = addressRoute;
    return this;
  }

   /**
   * The route of the organization location
   * @return addressRoute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The route of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_ROUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressRoute() {
    return addressRoute;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_ROUTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressRoute(String addressRoute) {
    this.addressRoute = addressRoute;
  }


  public OrganizationItem addressSublocality(String addressSublocality) {
    
    this.addressSublocality = addressSublocality;
    return this;
  }

   /**
   * The sub-locality of the organization location
   * @return addressSublocality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The sub-locality of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_SUBLOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressSublocality() {
    return addressSublocality;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_SUBLOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressSublocality(String addressSublocality) {
    this.addressSublocality = addressSublocality;
  }


  public OrganizationItem addressLocality(String addressLocality) {
    
    this.addressLocality = addressLocality;
    return this;
  }

   /**
   * The locality of the organization location
   * @return addressLocality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The locality of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressLocality() {
    return addressLocality;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LOCALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLocality(String addressLocality) {
    this.addressLocality = addressLocality;
  }


  public OrganizationItem addressAdminAreaLevel1(String addressAdminAreaLevel1) {
    
    this.addressAdminAreaLevel1 = addressAdminAreaLevel1;
    return this;
  }

   /**
   * The level 1 admin area of the organization location
   * @return addressAdminAreaLevel1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The level 1 admin area of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressAdminAreaLevel1() {
    return addressAdminAreaLevel1;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressAdminAreaLevel1(String addressAdminAreaLevel1) {
    this.addressAdminAreaLevel1 = addressAdminAreaLevel1;
  }


  public OrganizationItem addressAdminAreaLevel2(String addressAdminAreaLevel2) {
    
    this.addressAdminAreaLevel2 = addressAdminAreaLevel2;
    return this;
  }

   /**
   * The level 2 admin area of the organization location
   * @return addressAdminAreaLevel2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The level 2 admin area of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressAdminAreaLevel2() {
    return addressAdminAreaLevel2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_ADMIN_AREA_LEVEL2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressAdminAreaLevel2(String addressAdminAreaLevel2) {
    this.addressAdminAreaLevel2 = addressAdminAreaLevel2;
  }


  public OrganizationItem addressCountry(String addressCountry) {
    
    this.addressCountry = addressCountry;
    return this;
  }

   /**
   * The country of the organization location
   * @return addressCountry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressCountry() {
    return addressCountry;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
  }


  public OrganizationItem addressPostalCode(String addressPostalCode) {
    
    this.addressPostalCode = addressPostalCode;
    return this;
  }

   /**
   * The postal code of the organization location
   * @return addressPostalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The postal code of the organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressPostalCode() {
    return addressPostalCode;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressPostalCode(String addressPostalCode) {
    this.addressPostalCode = addressPostalCode;
  }


  public OrganizationItem addressFormattedAddress(String addressFormattedAddress) {
    
    this.addressFormattedAddress = addressFormattedAddress;
    return this;
  }

   /**
   * The formatted organization location
   * @return addressFormattedAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The formatted organization location")
  @JsonProperty(JSON_PROPERTY_ADDRESS_FORMATTED_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressFormattedAddress() {
    return addressFormattedAddress;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_FORMATTED_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressFormattedAddress(String addressFormattedAddress) {
    this.addressFormattedAddress = addressFormattedAddress;
  }


  public OrganizationItem openDealsCount(Integer openDealsCount) {
    
    this.openDealsCount = openDealsCount;
    return this;
  }

   /**
   * The count of open deals related with the item
   * @return openDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of open deals related with the item")
  @JsonProperty(JSON_PROPERTY_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOpenDealsCount() {
    return openDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenDealsCount(Integer openDealsCount) {
    this.openDealsCount = openDealsCount;
  }


  public OrganizationItem relatedOpenDealsCount(Integer relatedOpenDealsCount) {
    
    this.relatedOpenDealsCount = relatedOpenDealsCount;
    return this;
  }

   /**
   * The count of related open deals related with the item
   * @return relatedOpenDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related open deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedOpenDealsCount() {
    return relatedOpenDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_OPEN_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedOpenDealsCount(Integer relatedOpenDealsCount) {
    this.relatedOpenDealsCount = relatedOpenDealsCount;
  }


  public OrganizationItem closedDealsCount(Integer closedDealsCount) {
    
    this.closedDealsCount = closedDealsCount;
    return this;
  }

   /**
   * The count of closed deals related with the item
   * @return closedDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of closed deals related with the item")
  @JsonProperty(JSON_PROPERTY_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getClosedDealsCount() {
    return closedDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosedDealsCount(Integer closedDealsCount) {
    this.closedDealsCount = closedDealsCount;
  }


  public OrganizationItem relatedClosedDealsCount(Integer relatedClosedDealsCount) {
    
    this.relatedClosedDealsCount = relatedClosedDealsCount;
    return this;
  }

   /**
   * The count of related closed deals related with the item
   * @return relatedClosedDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related closed deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedClosedDealsCount() {
    return relatedClosedDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_CLOSED_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedClosedDealsCount(Integer relatedClosedDealsCount) {
    this.relatedClosedDealsCount = relatedClosedDealsCount;
  }


  public OrganizationItem wonDealsCount(Integer wonDealsCount) {
    
    this.wonDealsCount = wonDealsCount;
    return this;
  }

   /**
   * The count of won deals related with the item
   * @return wonDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of won deals related with the item")
  @JsonProperty(JSON_PROPERTY_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWonDealsCount() {
    return wonDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWonDealsCount(Integer wonDealsCount) {
    this.wonDealsCount = wonDealsCount;
  }


  public OrganizationItem relatedWonDealsCount(Integer relatedWonDealsCount) {
    
    this.relatedWonDealsCount = relatedWonDealsCount;
    return this;
  }

   /**
   * The count of related won deals related with the item
   * @return relatedWonDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related won deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedWonDealsCount() {
    return relatedWonDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_WON_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedWonDealsCount(Integer relatedWonDealsCount) {
    this.relatedWonDealsCount = relatedWonDealsCount;
  }


  public OrganizationItem lostDealsCount(Integer lostDealsCount) {
    
    this.lostDealsCount = lostDealsCount;
    return this;
  }

   /**
   * The count of lost deals related with the item
   * @return lostDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of lost deals related with the item")
  @JsonProperty(JSON_PROPERTY_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLostDealsCount() {
    return lostDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLostDealsCount(Integer lostDealsCount) {
    this.lostDealsCount = lostDealsCount;
  }


  public OrganizationItem relatedLostDealsCount(Integer relatedLostDealsCount) {
    
    this.relatedLostDealsCount = relatedLostDealsCount;
    return this;
  }

   /**
   * The count of related lost deals related with the item
   * @return relatedLostDealsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The count of related lost deals related with the item")
  @JsonProperty(JSON_PROPERTY_RELATED_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRelatedLostDealsCount() {
    return relatedLostDealsCount;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_LOST_DEALS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedLostDealsCount(Integer relatedLostDealsCount) {
    this.relatedLostDealsCount = relatedLostDealsCount;
  }


  public OrganizationItem nextActivityDate(String nextActivityDate) {
    
    this.nextActivityDate = nextActivityDate;
    return this;
  }

   /**
   * The date of the next activity associated with the deal
   * @return nextActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityDate() {
    return nextActivityDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityDate(String nextActivityDate) {
    this.nextActivityDate = nextActivityDate;
  }


  public OrganizationItem nextActivityTime(String nextActivityTime) {
    
    this.nextActivityTime = nextActivityTime;
    return this;
  }

   /**
   * The time of the next activity associated with the deal
   * @return nextActivityTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time of the next activity associated with the deal")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActivityTime() {
    return nextActivityTime;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivityTime(String nextActivityTime) {
    this.nextActivityTime = nextActivityTime;
  }


  public OrganizationItem nextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
    
    return this;
  }

   /**
   * The ID of the next activity associated with the deal
   * @return nextActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the next activity associated with the deal")
  @JsonIgnore

  public Integer getNextActivityId() {
        return nextActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getNextActivityId_JsonNullable() {
    return nextActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY_ID)
  public void setNextActivityId_JsonNullable(JsonNullable<Integer> nextActivityId) {
    this.nextActivityId = nextActivityId;
  }

  public void setNextActivityId(Integer nextActivityId) {
    this.nextActivityId = JsonNullable.<Integer>of(nextActivityId);
  }


  public OrganizationItem lastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
    
    return this;
  }

   /**
   * The ID of the last activity associated with the deal
   * @return lastActivityId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the last activity associated with the deal")
  @JsonIgnore

  public Integer getLastActivityId() {
        return lastActivityId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLastActivityId_JsonNullable() {
    return lastActivityId;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_ID)
  public void setLastActivityId_JsonNullable(JsonNullable<Integer> lastActivityId) {
    this.lastActivityId = lastActivityId;
  }

  public void setLastActivityId(Integer lastActivityId) {
    this.lastActivityId = JsonNullable.<Integer>of(lastActivityId);
  }


  public OrganizationItem lastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
    
    return this;
  }

   /**
   * The date of the last activity associated with the deal
   * @return lastActivityDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of the last activity associated with the deal")
  @JsonIgnore

  public String getLastActivityDate() {
        return lastActivityDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastActivityDate_JsonNullable() {
    return lastActivityDate;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY_DATE)
  public void setLastActivityDate_JsonNullable(JsonNullable<String> lastActivityDate) {
    this.lastActivityDate = lastActivityDate;
  }

  public void setLastActivityDate(String lastActivityDate) {
    this.lastActivityDate = JsonNullable.<String>of(lastActivityDate);
  }


  public OrganizationItem editName(Boolean editName) {
    
    this.editName = editName;
    return this;
  }

   /**
   * If the company ID of the organization and company ID of the request is same or not
   * @return editName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the company ID of the organization and company ID of the request is same or not")
  @JsonProperty(JSON_PROPERTY_EDIT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEditName() {
    return editName;
  }


  @JsonProperty(JSON_PROPERTY_EDIT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditName(Boolean editName) {
    this.editName = editName;
  }


  public OrganizationItem lastActivity(Object lastActivity) {
    
    this.lastActivity = lastActivity;
    return this;
  }

   /**
   * Please refer to response schema of &lt;a href&#x3D;\&quot;https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\&quot;&gt;Activity&lt;/a&gt;
   * @return lastActivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>")
  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLastActivity() {
    return lastActivity;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastActivity(Object lastActivity) {
    this.lastActivity = lastActivity;
  }


  public OrganizationItem nextActivity(Object nextActivity) {
    
    this.nextActivity = nextActivity;
    return this;
  }

   /**
   * Please refer to response schema of &lt;a href&#x3D;\&quot;https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\&quot;&gt;Activity&lt;/a&gt;
   * @return nextActivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Please refer to response schema of <a href=\"https://developers.pipedrive.com/docs/api/v1/Activities#getActivity\">Activity</a>")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getNextActivity() {
    return nextActivity;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextActivity(Object nextActivity) {
    this.nextActivity = nextActivity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationItem organizationItem = (OrganizationItem) o;
    return Objects.equals(this.id, organizationItem.id) &&
        Objects.equals(this.companyId, organizationItem.companyId) &&
        Objects.equals(this.ownerId, organizationItem.ownerId) &&
        Objects.equals(this.name, organizationItem.name) &&
        Objects.equals(this.activeFlag, organizationItem.activeFlag) &&
        Objects.equals(this.pictureId, organizationItem.pictureId) &&
        Objects.equals(this.countryCode, organizationItem.countryCode) &&
        Objects.equals(this.firstChar, organizationItem.firstChar) &&
        Objects.equals(this.addTime, organizationItem.addTime) &&
        Objects.equals(this.updateTime, organizationItem.updateTime) &&
        Objects.equals(this.visibleTo, organizationItem.visibleTo) &&
        Objects.equals(this.label, organizationItem.label) &&
        Objects.equals(this.ownerName, organizationItem.ownerName) &&
        Objects.equals(this.ccEmail, organizationItem.ccEmail) &&
        Objects.equals(this.emailMessagesCount, organizationItem.emailMessagesCount) &&
        Objects.equals(this.peopleCount, organizationItem.peopleCount) &&
        Objects.equals(this.activitiesCount, organizationItem.activitiesCount) &&
        Objects.equals(this.doneActivitiesCount, organizationItem.doneActivitiesCount) &&
        Objects.equals(this.undoneActivitiesCount, organizationItem.undoneActivitiesCount) &&
        Objects.equals(this.filesCount, organizationItem.filesCount) &&
        Objects.equals(this.notesCount, organizationItem.notesCount) &&
        Objects.equals(this.followersCount, organizationItem.followersCount) &&
        Objects.equals(this.address, organizationItem.address) &&
        Objects.equals(this.addressSubpremise, organizationItem.addressSubpremise) &&
        Objects.equals(this.addressStreetNumber, organizationItem.addressStreetNumber) &&
        Objects.equals(this.addressRoute, organizationItem.addressRoute) &&
        Objects.equals(this.addressSublocality, organizationItem.addressSublocality) &&
        Objects.equals(this.addressLocality, organizationItem.addressLocality) &&
        Objects.equals(this.addressAdminAreaLevel1, organizationItem.addressAdminAreaLevel1) &&
        Objects.equals(this.addressAdminAreaLevel2, organizationItem.addressAdminAreaLevel2) &&
        Objects.equals(this.addressCountry, organizationItem.addressCountry) &&
        Objects.equals(this.addressPostalCode, organizationItem.addressPostalCode) &&
        Objects.equals(this.addressFormattedAddress, organizationItem.addressFormattedAddress) &&
        Objects.equals(this.openDealsCount, organizationItem.openDealsCount) &&
        Objects.equals(this.relatedOpenDealsCount, organizationItem.relatedOpenDealsCount) &&
        Objects.equals(this.closedDealsCount, organizationItem.closedDealsCount) &&
        Objects.equals(this.relatedClosedDealsCount, organizationItem.relatedClosedDealsCount) &&
        Objects.equals(this.wonDealsCount, organizationItem.wonDealsCount) &&
        Objects.equals(this.relatedWonDealsCount, organizationItem.relatedWonDealsCount) &&
        Objects.equals(this.lostDealsCount, organizationItem.lostDealsCount) &&
        Objects.equals(this.relatedLostDealsCount, organizationItem.relatedLostDealsCount) &&
        Objects.equals(this.nextActivityDate, organizationItem.nextActivityDate) &&
        Objects.equals(this.nextActivityTime, organizationItem.nextActivityTime) &&
        equalsNullable(this.nextActivityId, organizationItem.nextActivityId) &&
        equalsNullable(this.lastActivityId, organizationItem.lastActivityId) &&
        equalsNullable(this.lastActivityDate, organizationItem.lastActivityDate) &&
        Objects.equals(this.editName, organizationItem.editName) &&
        Objects.equals(this.lastActivity, organizationItem.lastActivity) &&
        Objects.equals(this.nextActivity, organizationItem.nextActivity);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, companyId, ownerId, name, activeFlag, pictureId, countryCode, firstChar, addTime, updateTime, visibleTo, label, ownerName, ccEmail, emailMessagesCount, peopleCount, activitiesCount, doneActivitiesCount, undoneActivitiesCount, filesCount, notesCount, followersCount, address, addressSubpremise, addressStreetNumber, addressRoute, addressSublocality, addressLocality, addressAdminAreaLevel1, addressAdminAreaLevel2, addressCountry, addressPostalCode, addressFormattedAddress, openDealsCount, relatedOpenDealsCount, closedDealsCount, relatedClosedDealsCount, wonDealsCount, relatedWonDealsCount, lostDealsCount, relatedLostDealsCount, nextActivityDate, nextActivityTime, hashCodeNullable(nextActivityId), hashCodeNullable(lastActivityId), hashCodeNullable(lastActivityDate), editName, lastActivity, nextActivity);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    activeFlag: ").append(toIndentedString(activeFlag)).append("\n");
    sb.append("    pictureId: ").append(toIndentedString(pictureId)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    firstChar: ").append(toIndentedString(firstChar)).append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    visibleTo: ").append(toIndentedString(visibleTo)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    ccEmail: ").append(toIndentedString(ccEmail)).append("\n");
    sb.append("    emailMessagesCount: ").append(toIndentedString(emailMessagesCount)).append("\n");
    sb.append("    peopleCount: ").append(toIndentedString(peopleCount)).append("\n");
    sb.append("    activitiesCount: ").append(toIndentedString(activitiesCount)).append("\n");
    sb.append("    doneActivitiesCount: ").append(toIndentedString(doneActivitiesCount)).append("\n");
    sb.append("    undoneActivitiesCount: ").append(toIndentedString(undoneActivitiesCount)).append("\n");
    sb.append("    filesCount: ").append(toIndentedString(filesCount)).append("\n");
    sb.append("    notesCount: ").append(toIndentedString(notesCount)).append("\n");
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressSubpremise: ").append(toIndentedString(addressSubpremise)).append("\n");
    sb.append("    addressStreetNumber: ").append(toIndentedString(addressStreetNumber)).append("\n");
    sb.append("    addressRoute: ").append(toIndentedString(addressRoute)).append("\n");
    sb.append("    addressSublocality: ").append(toIndentedString(addressSublocality)).append("\n");
    sb.append("    addressLocality: ").append(toIndentedString(addressLocality)).append("\n");
    sb.append("    addressAdminAreaLevel1: ").append(toIndentedString(addressAdminAreaLevel1)).append("\n");
    sb.append("    addressAdminAreaLevel2: ").append(toIndentedString(addressAdminAreaLevel2)).append("\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("    addressPostalCode: ").append(toIndentedString(addressPostalCode)).append("\n");
    sb.append("    addressFormattedAddress: ").append(toIndentedString(addressFormattedAddress)).append("\n");
    sb.append("    openDealsCount: ").append(toIndentedString(openDealsCount)).append("\n");
    sb.append("    relatedOpenDealsCount: ").append(toIndentedString(relatedOpenDealsCount)).append("\n");
    sb.append("    closedDealsCount: ").append(toIndentedString(closedDealsCount)).append("\n");
    sb.append("    relatedClosedDealsCount: ").append(toIndentedString(relatedClosedDealsCount)).append("\n");
    sb.append("    wonDealsCount: ").append(toIndentedString(wonDealsCount)).append("\n");
    sb.append("    relatedWonDealsCount: ").append(toIndentedString(relatedWonDealsCount)).append("\n");
    sb.append("    lostDealsCount: ").append(toIndentedString(lostDealsCount)).append("\n");
    sb.append("    relatedLostDealsCount: ").append(toIndentedString(relatedLostDealsCount)).append("\n");
    sb.append("    nextActivityDate: ").append(toIndentedString(nextActivityDate)).append("\n");
    sb.append("    nextActivityTime: ").append(toIndentedString(nextActivityTime)).append("\n");
    sb.append("    nextActivityId: ").append(toIndentedString(nextActivityId)).append("\n");
    sb.append("    lastActivityId: ").append(toIndentedString(lastActivityId)).append("\n");
    sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
    sb.append("    editName: ").append(toIndentedString(editName)).append("\n");
    sb.append("    lastActivity: ").append(toIndentedString(lastActivity)).append("\n");
    sb.append("    nextActivity: ").append(toIndentedString(nextActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

