deal:
  commercial-training:
    name:
    id :
  account-manager:
    name:
    id:
  portfolio:
    name:
    id:
org:
  commercial-training:
    name:
    id:
  account-manager:
    name:
    id:
  portfolio:
    name:
    id:
api-client: ${API_name}
uri-pipedrive: https://zenika-sandbox.pipedrive.com/v1/