deal:
  commercial-training:
    name: Commercial Training [Datalink]
    id: 12514
  account-manager:
    name: Account Manager Training [Datalink]
    id: 12511
  portfolio:
    name: Portfolio [Datalink]
    id: 12515
org:
  commercial-training:
    name: Commercial Training
    id: 4023
  account-manager:
    name: Account Manager Training
    id: 4022
  portfolio:
    name: Customer Portfolio
    id: 4025
api-client: ${API_KEY}
uri-pipedrive: https://zenika.pipedrive.com/v1/